### ISSUE TITLE
Add collection "GenHiggsSister"

### ISSUE THREAD

**Issue by azzurrip** [vhbb/cmssw#110]
all other genparticles daughters of the Higgs mother 
(where the Higgs mother has pdgId!=25., ie is not a Higgs copy).

Will add ISR partons and, most importantly, quarks from the VBF 
production, so we can measure matching efficiencies with jets.

**Comment by arizzi** [comment]
pdgId 15? or status 15?
I think you need to provide some code here...
please also consider having a look at existing Heppy collections produced by GeneratorAnalyzer to see if something fits what you want

**Comment by azzurrip** [comment]
sorry was a typo, I meant pdgid not 25 , ie
the higgs mother must not be a higgs boson,
is so we need to up to find a mother that  is not a higgs boson

**Comment by arizzi** [comment]
added more stuff, perhaps we can optimize later and add just the sisters, we should review checking the overal size with current approach

**Comment by azzurrip** [comment]
Made a test tree on VBF Hbb signal.
Unfortunately the GenSummary collection never includes the VBF quark legs 
that was the main need here ...

**Comment by arizzi** [comment]
can you show a printouT?

**Comment by azzurrip** [comment]
See below on a VBF Hbb powheg-pythia tree

The collection often only has the H->bb particles (3), plus sometimes you may get some other radiation particles, but never the VBF qq legs 

tree>Scan("nGenSummary:GenSummary_pdgId:GenSummary_motherIndex:GenSummary_pt:GenSummary_eta:GenSummary_phi")
***********************************************************************************************
*    Row   * Instance * nGenSumma * GenSummar * GenSummar * GenSummar * GenSummar * GenSummar *
***********************************************************************************************
*        0 *        0 *         5 *         4 *        -1 * 54.264583 * 4.0489912 * -0.916467 *
*        0 *        1 *         5 *        21 *        -1 * 74.796608 * -2.720728 * -0.685258 *
*        0 *        2 *         5 *        25 *        -1 * 119.48430 * 2.4359729 * 2.5677774 *
*        0 *        3 *         5 *         5 *         2 * 113.98436 * 2.1236252 * 2.0952458 *
*        0 *        4 *         5 *        -5 *         2 * 54.909862 * 2.0406889 * -2.478412 *
*        1 *        0 *         3 *        25 *        -1 * 38.297641 * -3.574209 * -0.302973 *
*        1 *        1 *         3 *         5 *         0 * 67.080337 * -2.085105 * 0.5560106 *
*        1 *        2 *         3 *        -5 *         0 * 51.090877 * -2.795778 * -1.982018 *
*        2 *        0 *         3 *        25 *        -1 * 105.42270 * -1.804475 * -0.882986 *
*        2 *        1 *         3 *         5 *         0 * 21.231126 * 0.2214920 * -1.264440 *
*        2 *        2 *         3 *        -5 *         0 * 86.081199 * -2.012820 * -0.791039 *
*        3 *        0 *         3 *        25 *        -1 * 130.29414 * 1.2798156 * -0.340733 *
*        3 *        1 *         3 *         5 *         0 * 12.068449 * 3.0465350 * 0.5358349 *
*        3 *        2 *         3 *        -5 *         0 * 122.92327 * 0.6752918 * -0.416260 *
*        4 *        0 *         3 *        25 *        -1 * 246.85356 * -1.753236 * 2.4476304 *
*        4 *        1 *         3 *         5 *         0 * 128.07217 * -1.219253 * 2.5738775 *
*        4 *        2 *         3 *        -5 *         0 * 120.88109 * -2.114289 * 2.3138291 *

**Comment by arizzi** [comment]
so let's remove the gensummary and write some code for that... volunteers?
