### ISSUE TITLE
Make QGL less lazy 

### ISSUE THREAD

**Issue by azzurrip** [vhbb/cmssw#119]
Needed for fully hadronic ttH (on 8 pt-leading central jets),
and useful for VH b-jet likelihood. 

Is it possible to run it on all jets with pT>20 ?

**Comment by arizzi** [comment]
need faster code

**Comment by arizzi** [comment]
btw for VH b-jet likelihood we better use b-tagging, I'd not be very happy to throw stuff into an MVA just because "everything adds something"... why QGL should help the VH b-jet likelihood?

**Comment by azzurrip** [comment]
Should add discrimination against the ISR jets (gluons).
It was suggested/requested to check during the last Hbb meeting. 
If it does not improve much we indeed can stick to using 
only jet b-tagging and pT, that works fine.
