### ISSUE TITLE
Handle real data

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#132]
implement switches to run on real data

**Comment by arizzi** [comment]
@degrutto I'm checking the vhbb_data.py, it seems to me that many ISMC switches should not be there but rather in the analyzers that should not attempt MC prodcedures (such as smearing) on non MC samples. Did you check that it was actually needed?

the _data file also seem quite out of sync

**Comment by degrutto** [comment]
Hi Andrea, 
the one in github is different from another test I did and used for trigger studies 
/afs/cern.ch/user/d/degrutto/public/forGK/vhbb_data.py
(you said not to commit it ;-) )

I would start looking at this, it shoud have less isMC or none actually

**Comment by arizzi** [comment]
I still see things such as

#                 NTupleVariable("nPU0", lambda ev : [bx.nPU() for bx in
 ev.pileUpInfo if bx.getBunchCrossing()==0][0], help="nPU in BX=0"),  <--
not for data?

that are NOT supposed to be handled commenting it out but rather adding the
option mcOnly=True in the NtupleVariable definition

**Comment by arizzi** [comment]
this is wrong!
FlagsAna.processName = 'HLT' # for data

should be 'RECO'

**Comment by arizzi** [comment]
started implementing in #148 , still have to fix trigger and substructures stuff

**Comment by arizzi** [comment]
#160 also fix the preprocessor
