### ISSUE TITLE
make list of triggers for data

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#135]

**Comment by arizzi** [comment]
@silviodonato are the trigger we currently have in the config ok for data?

**Comment by silviodonato** [comment]
No, but I prepared a PR https://github.com/vhbb/cmssw/pull/136 with the trigger table for data

**Comment by arizzi** [comment]
is there an chance to have the same table for data and mc? or the menu in
MC is completely wrong?
how about the 25ns campaign, was the trigger table fixed to the most recent
one?
should we have a different table for 25ns MC ?

**Comment by silviodonato** [comment]
The comparison of data vs mc trigger table is here:
https://docs.google.com/spreadsheets/d/1m7rAF1BBnTuxdElk3x0s_DuC4zOOTWgYDgbRnLnUt_I/edit#gid=252529807
As you can see the name of all trigger with MHT have been changed from "IDLoose" to "IDTight",
the trigger with electron have been changed WP75/WP85 -> WPTight/WPLoose
the trigger with b-tagging have different working point.

About 25ns MC, I think it uses the same trigger table as 50ns MC, but let me check.

**Comment by silviodonato** [comment]
The triggerTable was already synchronized with the 25ns Spring15 MC.

**Comment by arizzi** [comment]
done in #136
