### ISSUE TITLE
update muon and ele id in vhbb

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#139]
see for muon 

 https://github.com/CERN-PH-CMG/cmg-cmssw/pull/477

and for ele

https://hypernews.cern.ch/HyperNews/CMS/get/higgs/1638.html

**Comment by capalmer85** [comment]
For electron ids the 50 ns tight (for barrel) is not appropriate for us.  It is not tighter than the HLT.  Conveners are aware and should fix it.  In the meantime, I don't want us to use it.

https://hypernews.cern.ch/HyperNews/CMS/get/higgs/1638/1.html

I worked on alternative IDs that would be suitable for single electron triggers can be found in this talk:
https://indico.cern.ch/event/370506/contribution/3/attachments/1135177/1624042/egamma_aug3_electronID.pdf

**Comment by degrutto** [comment]
Hi Chris,

very good you are involved into it.
Have your proposals be put as a new label in miniaod or so so that we can use it? or do you want to apply as sequential cuts in our vhbb istance? If so, would you write the code?

**Comment by capalmer85** [comment]
E/gamma does not want more cut-based IDs than they absolutely have to have, but so far they haven't acceptably fixed the posted ID.  I would be happy to implement my ID as a temporary solution.  If you point me to where I should put that code, I'll do it by the end of the week.

**Comment by degrutto** [comment]
ok, I understand the selection is done here


https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/test/vhbb.py#L214

**Comment by arizzi** [comment]
so we wait for new MiniAOD on V14 ?

**Comment by degrutto** [comment]
yes we wait for the new MiniAOD version

**Comment by arizzi** [comment]
please check #207 and let me know if there is something more you want

**Comment by degrutto** [comment]
close this, as we have #229 open
