### ISSUE TITLE
Add color flow (pull angle) variables

### ISSUE THREAD

**Issue by bortigno** [vhbb/cmssw#140]
I will try to implement the color flow (pull angle) in the ntuples.

**Comment by arizzi** [comment]
should we implement it our old way or use recent substructures fastjet  machinery for that?

**Comment by bortigno** [comment]
I would start our old way. I am not 100% sure I understand what you mean by substructure machinery, but if it is what theorist call "dipolarity" we could use that name to refer to it and implement it after the "pull angle"?

**Comment by bortigno** [comment]
I added two jet based color flow variable :  the phi and the magnitude of the pull vector in the eta,phi plane for the higgs jets so anyone can compute the pull angle against any other jets. could be useful for the FSR or semileptonic TTbar and single top. pull request #151

**Comment by arizzi** [comment]
I moved the target to V14, but if you are ready earlier we can pick it

**Comment by bortigno** [comment]
#151  please review - it is ~10 times faster. thank you.

**Comment by arizzi** [comment]
indirectly merged
