### ISSUE TITLE
new genJet collections with missing energy

### ISSUE THREAD

**Issue by dcurry09** [vhbb/cmssw#149]
Hi,  Starting in v12 I've seen a reduction in the genJet energy compared to v11.  Both the withNu and withoutNu genJet collections seem to have the same energy.  The effect is that jet_mcPt is now lower than jet_pt.

Thanks!

**Comment by jpata** [comment]
this is probably related to #145. We accidentally replced genjets with the reclustered version.

**Comment by degrutto** [comment]
For the b-jet energy regression, I guess what we need is to make sure is that Jet_genJet leave is pointing to the matched genJet_pt with neutrinos. This would avoid the analysts to make the matching between two collections before evaluating the regression

**Comment by arizzi** [comment]
@degrutto, the withNu was meant to do that but as @jpata said we accidentally replaced the genJets with some not having the "withNu" info

**Comment by azzurrip** [comment]
to summarise, my understanding is this (please correct me in case) 
in V12 we have
Jet_mcPt from the matched GenJet of the standard miniAOD GenJet collection (without Nu)
GenJet_pt  from the "accidentally" fully reclustered and replaced GenJets (with Nu)
GenJet_wNuPt just a copy of GenJet_pt (with Nu)

in V13 we should not recluster GenJets, but use the standard collection (without Nu) and add the 
neutrino as planned in V12. So
GenJet_pt  will have the standard GenJet (without Nu)
GenJet_wNuPt will have standard GenJet corrected (with Nu)
Jet_mcPt:  it would be nice if here we have the GenJet_wNuPt value of the corresponding matched GenJet, Will it be the case ? I think this is what Michele @degrutto was asking for.

**Comment by arizzi** [comment]
should be fixed by #156 please validate
