### ISSUE TITLE
Limit the HCSV jet pair among the collection of saved pt-leading jets

### ISSUE THREAD

**Issue by azzurrip** [vhbb/cmssw#154]
to avoid the occurrence of best CSV jets outside the list of saved jets, i.e.
situations with hJCidx out of the  bounds of the Jet_xx arrays,
that creates problems to check the chosen b-jet properties.

**Comment by arizzi** [comment]
this was fixed already, and reverted by mistake will be fixed again

**Comment by arizzi** [comment]
@azzurrip is it ok if I just store up to 25 jets?

**Comment by azzurrip** [comment]
sure more than enough

On 18 Sep 2015, at 15:34, arizzi <notifications@github.com<mailto:notifications@github.com>> wrote:


@azzurrip<https://github.com/azzurrip> is it ok if I just store up to 25 jets?
