### ISSUE TITLE
jet corrections and smearing for V13

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#159]
In the ttH reference analysis we found that we seem to be using old JEC/JER.

JEC
-------
We seem to be still using the Phys14 JECs: https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/test/vhbb.py#L210
According to https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions the latest JEC for 25ns is in `MCRUN2_74_V9`. OK to get the txt files, put to `test/jec` folder and switch the JEC? 

JER
-----
Heppy seems to use the 7 TeV JER recipe: https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L362
There was a suggestion to switch to the 8TeV scale factors. https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetResolution#JER_Scaling_factors_and_Uncertai

@arizzi @degrutto @bianchini what do you think? I can make a PR for this.

**Comment by arizzi** [comment]
new jec have been copied already, I may not have switched the default yet... I'll do

**Comment by jpata** [comment]
These are only for 50ns though? At least by filename.

**Comment by arizzi** [comment]
there is another tar file somewhere with 25ns payloads, but now they also created (finally) the GTs, so we could dump ourself.
Please note that I moved the jec folder.

**Comment by jpata** [comment]
Thanks for the reply. I just extracted the MCRUN2 25ns jecs using a cmssw config.

**Comment by jpata** [comment]
I updated the JER: https://github.com/cbernet/cmssw/pull/52
25ns JEC-s in a separate PR.

**Comment by jpata** [comment]
Ciao, I updated both JECs and JERs now. Running a larger scale test to check for anomalies.

**Comment by jpata** [comment]
Might be relevant: https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/1630.html
@bianchini @arizzi

**Comment by jpata** [comment]
* JER has been merged by Colin
   * JECs have been merged, but I forgot to commit some files: https://github.com/vhbb/cmssw/pull/169
Otherwise I consider this to be solved.

**Comment by arizzi** [comment]
@jpata I should have merged latest colin stuff, can you cross check and we close this in case?

**Comment by degrutto** [comment]
Hi guys,
on a different front, are we correcting the AK8 jets? To me it does not seems the case

**Comment by jpata** [comment]
just tested locally on HEAD, seems good to me: JECs are there, JER is updated, discarded jets are kept. feel free to close.
