### ISSUE TITLE
pu weight

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#164]
implement pu weight based on data lumi profile

**Comment by arizzi** [comment]
need some progress from https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/488/2/1/2/1/2/1.html

**Comment by perrozzi** [comment]
for the record, the new json is out
https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2496.html
---- Golden JSON
/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/Cert_246908-256869_13TeV_PromptReco_Collisions15_25ns_JSON.txt
with recorded luminosity, based on brilcalc: 166.37/pb

**Comment by arizzi** [comment]
done in #190

**Comment by degrutto** [comment]
Hi Andrea,

for reference, can you share the instructions you used to get the puStartup2015.root? or the central location you took it from (if any)? thanks

**Comment by arizzi** [comment]
I made it myself from the sample config
