### ISSUE TITLE
Spring15 lepton isolation: effective area

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#175]
We seem to be using Phys14 effective areas in heppy
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/LeptonAnalyzer.py#L296

whereas spring15 EA values are now available.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/CutBasedElectronIdentificationRun2#Spring15_selection_25ns -> EGM presentation ([1], slide 4) -> another presentation with EA values ([2], slide 12).

[1] https://indico.cern.ch/event/370507/contribution/1/attachments/1140657/1633761/Rami_eleCB_ID_25ns.pdf
[2] https://indico.cern.ch/event/369239/contribution/4/attachments/1134761/1623262/talk_effective_areas_25ns.pdf

As we cannot re-calculate relIso offline (on top of vhbb ntuples), nor is it easy or reasonable to add, this should be fixed before V13.

I'm updating the values now and will make a PR against Colin tomorrow.

@arizzi @bianchini

**Comment by mariadalfonso** [comment]
Hi Joseep.
In CMG we already added the Spring15 wp
https://github.com/CERN-PH-CMG/cmg-cmssw/pull/501/files

We can PR to colin all the files in our heppy branch.

@gpetruc

Maria

**Comment by jpata** [comment]
@mariadalfonso thanks, that would be perfect. Then I won't duplicate on my side.

**Comment by arizzi** [comment]
@jpata should meanwhile take this?

**Comment by jpata** [comment]
@arizzi: it would be good if we can merge from CMG. Should I backport(cherrypick) that commit to 747p1?

**Comment by arizzi** [comment]
yes please

**Comment by arizzi** [comment]
@azzurip @degrutto @jpata this is a showstopper right for V13 right?

**Comment by jpata** [comment]
Sorry i was overtaken by an upcoming presentation. Can i still do today?
29.09.2015 4:54 PM kirjutas kuupäeval "arizzi" <notifications@github.com>:

**Comment by arizzi** [comment]
sure, let's try to close V13 by tomorrow

**Comment by jpata** [comment]
Done: https://github.com/vhbb/cmssw/pull/188
Checking.
