### ISSUE TITLE
MET PUPPI phi

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#183]
The variable metPuppi_phi is missing, we should add it.

**Comment by arizzi** [comment]
cab you check if it was already in V13 PRs ?

**Comment by silviodonato** [comment]
It seems that it is not in V13: https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/test/vhbb.py#L54.
I've prepared a simple PR: https://github.com/vhbb/cmssw/compare/vhbbHeppy74X...silviodonato:patch-4
