### ISSUE TITLE
Add AK08 corrections, and cut on corrected groomed jets for boosted VH/ttH

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#185]

**Comment by arizzi** [comment]
What does it mean?

**Comment by degrutto** [comment]
Hi Andrea, we are currently not correcting the fatjet, so when we decide to run the AK08 and CA15 sequences we are doing it when the uncorrected pt is greater than X (not X = 200 GeV). As there are AK08 correction available by JetMET group. I would use them and cut on the corrected pt. This is not critical now but will become if we want to use indeed the boosted topology for VH and ttH. Hope it is clear now

**Comment by degrutto** [comment]
for the record,
this is not critical, but we need at a certain time to apply the AK08 correction,
the prescription according to exo vv analysis is to do just the L2L3 (data/MC) +residual correction (for data) and propagate to the mass (so no L1 corrections)

I remove this from V14, but leave the issue open

**Comment by degrutto** [comment]
fixed in #250 (actually JEC for AK08 and AK04 needs to be updated anyway again for 76X)
