### ISSUE TITLE
Add HLT_PFHT350 to list of trigger bits & fix individual trigger bit counts

### ISSUE THREAD

**Issue by d-salerno** [vhbb/cmssw#186]
Hi,
Could we add HLT_PFHT350_v* to the trigger table? This is a reference trigger for the all hadronic ttH triggers.

Also, I had a problem that some of the individual trigger bits were showing up with zero hits, even though the group OR seemed to be working - for examples the paths in ttHhardonicHighLumi.

It was actually quite random as other individual paths showed hits. I though it may be because the paths appear in more than one group, but I never did figure it out.

Could you test this on some recent data and investigate if necessary?
Thanks,
Daniel

**Comment by silviodonato** [comment]
Hi Daniel,
I've included HLT_PFHT350_v with PR #225 . Do you need it also in the MC?
Regarding the bug, I don't know.... Is it possible that the problem arises when a trigger name is missing in data?

Cheers,
Silvio.

**Comment by d-salerno** [comment]
Hi Silvio,
Thanks for that. Yes, we also need it in the MC.
For the bug, the trigger names were definitely in the data, so that was not the issue. However, looking at some data produced with V13, I see the counts behaving well in HLT_BIT_HLT_PFHT400_SixJet30_BTagCSV0p55_2PFBTagCSV0p72_v and HLT_BIT_HLT_PFHT450_SixJet40_PFBTagCSV0p72_v so I guess it's no longer an issue.
It might have been a problem with my system in then end.
Cheers,
Daniel

**Comment by silviodonato** [comment]
Good for us.
I've just checked the trigger menu in MC (in Spring15 the menu is the default GRun in CMSSW_7_4_1, ie. /dev/CMSSW_7_4_0/GRun/V41) and I don't find HLT_PFHT350_v.

I'm afraid that it isn't inside the MC.
Silvio.

**Comment by d-salerno** [comment]
Hi Slivio,
HLT_PFHT350_v1 is in that menu you mentioned, it should be grouped together with all the other HT paths. If your using the testserver to browse the menu, it seems you can only search in whatever is visible on the screen.
In any case I thought the frozen menu's were used for MC production, so whatever the frozen menu was at the time for the release (This is the command used in the McM for Spring15: HLT:@frozen25ns)
The first frozen menu is /frozen/2015/25ns14e33/v1.0/HLT/V1 and HLT_PFHT350_v1 is in there too, so there should be no problem including HLT_PFHT350_v in the code.
Thanks,
Daniel

**Comment by silviodonato** [comment]
You are right, the trigger was in the menu.
I've updated the PR https://github.com/vhbb/cmssw/pull/225/files 

Silvio

**Comment by d-salerno** [comment]
Great! Thanks a lot!

**Comment by degrutto** [comment]
ok,
the PR from SIlvio is merged so we can close this, thanks
