### ISSUE TITLE
Check we are using latest JEC

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#201]
Currently it is 

JetAna.mcGT="MCRUN2_74_V9D"
JetAna.dataGT = "Summer15_50nsV4_DATA"

there should exist V5 for 25 ns and correspondent for MC!

**Comment by arizzi** [comment]
some one should dump the JECs into the /data folder and make a PR !

**Comment by degrutto** [comment]
see  #213

**Comment by degrutto** [comment]
close this, see #213
