### ISSUE TITLE
fix description of variable Jet_mcIdx

### ISSUE THREAD

**Issue by perrozzi** [vhbb/cmssw#203]
currently is the same as Jet_btagIdx:
Jet_btagIdx     ranking in btag  for Cental+fwd jets after full selection and cleaning, sorted by b-tag
Jet_mcIdx       ranking in btag  for Cental+fwd jets after full selection and cleaning, sorted by b-tag

**Comment by arizzi** [comment]
please make a PR

**Comment by perrozzi** [comment]
https://github.com/vhbb/cmssw/pull/209
