### ISSUE TITLE
add JER uncertainties, and fix JEC uncertainties 

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#204]
we would need to change shiftJER to +- 1

https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L428

**Comment by degrutto** [comment]
@arizzi @jpata do we want to have these in v14?

**Comment by perrozzi** [comment]
also JEC?
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L425

**Comment by degrutto** [comment]
don't we have JEC uncertainties already? do we want more uncertainties than just one, to cover for example high and low pt separately?

**Comment by jpata** [comment]
@perrozzi JEC we variate already with this: https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/physicsutils/JetReCalibrator.py#L107

maybe smarter to do smth similar for JER variations as well - store in place instead of making new collection.

**Comment by azzurrip** [comment]
Hi, concerning total JEC uncertainties.
In V12 they were filled in Jet_corr_JECDown and Jet_corr_JECUp
root [8] tree->Scan("nJet:Jet_pt:Jet_eta:Jet_id:Jet_puId:Jet_mcFlavour:Jet_hadronFlavour:Jet_corr_JECDown:Jet_corr:Jet_corr_JECUp")
***********************************************************************************************************************************************
*    Row   * Instance *      nJet *    Jet_pt *   Jet_eta *    Jet_id *  Jet_puId * Jet_mcFla * Jet_hadro * Jet_corr_ *  Jet_corr * Jet_corr_ *
***********************************************************************************************************************************************
*        0 *        0 *        15 * 193.74496 * 0.3838057 *         3 *         1 *        21 *         0 * 1.0425086 * 1.0501214 * 1.0577342 *
*        0 *        1 *        15 * 173.05935 * 0.1086308 *         3 *         1 *         2 *         0 * 1.0422524 * 1.0495836 * 1.0569149 *
*        0 *        2 *        15 * 50.638855 * 2.6970315 *         3 *         1 *         0 *         5 * 0.8561361 * 0.8765187 * 0.8969014 *
*        0 *        3 *        15 * 45.200111 * 3.2630300 *         3 *         1 *         0 *         0 * 1.4939830 * 1.5411077 * 1.5882325 *
*        0 *        4 *        15 * 43.038772 * 2.6820688 *         3 *         1 *        -5 *         5 * 0.7916592 * 0.8114141 * 0.8311691 *
*        0 *        5 *        15 * 37.089916 * -3.304039 *         3 *         1 *         0 *         0 * 1.4864169 * 1.5340344 * 1.5816520 *
*        0 *        6 *        15 * 27.490188 * -3.151461 *         3 *         0 *         0 *         0 * 1.4019546 * 1.4512840 * 1.5006134 *
*        0 *        7 *        15 * 24.075471 * 3.4999110 *         3 *         0 *         0 *         0 * 1.2105134 * 1.2546389 * 1.2987643 *
*        0 *        8 *        15 * 24.003444 * -2.928735 *         3 *         1 *        21 *         0 * 0.7323963 * 0.7549007 * 0.7774051 *

In V13 it's JECup/Down are just -99   !

Attaching file ZH_HToBB_ZToLL_M125_13TeV_powheg_pythia8__RunIISpring15DR74-Asympt25ns.root as _file0...
root [1] tree->Scan("nJet:Jet_pt:Jet_eta:Jet_id:Jet_puId:Jet_mcFlavour:Jet_hadronFlavour:Jet_corr_JECDown:Jet_corr:Jet_corr_JECUp")
***********************************************************************************************************************************************
*    Row   * Instance *      nJet *    Jet_pt *   Jet_eta *    Jet_id *  Jet_puId * Jet_mcFla * Jet_hadro * Jet_corr_ *  Jet_corr * Jet_corr_ *
***********************************************************************************************************************************************
*        0 *        0 *         5 * 64.952812 * 1.2627470 *         3 *         1 *        -5 *         5 *       -99 * 1.0092904 *       -99 *
*        0 *        1 *         5 * 27.663976 * 1.3890600 *         3 *         1 *         5 *         5 *       -99 * 0.9577506 *       -99 *
*        0 *        2 *         5 * 23.901393 * -0.039230 *         3 *         1 *         2 *         0 *       -99 * 0.9084250 *       -99 *
*        0 *        3 *         5 * 19.318077 * -0.895081 *         3 *         1 *        -1 *         0 *       -99 * 0.8818323 *       -99 *
*        0 *        4 *         5 * 15.387647 * -3.293248 *         3 *       -99 *         0 *         0 *       -99 * 0.9192376 *       -99 *
*        1 *        0 *         5 * 97.432205 * -0.459897 *         3 *         1 *         4 *         4 *       -99 * 1.0074316 *       -99 *
*        1 *        1 *         5 * 85.916069 * -1.670170 *         3 *         1 *        -5 *         5 *       -99 * 1.0407372 *       -99 *
*        1 *        2 *         5 * 73.784774 * -0.848315 *         3 *         1 *         5 *         5 *       -99 * 1.0072480 *       -99 *
*        1 *        3 *         5 * 22.134195 * -3.057020 *         3 *       -99 *         0 *         0 *       -99 * 0.9832379 *       -99 *
*        1 *        4 *         5 * 16.683137 * 4.2163338 *         1 *       -99 *         0 *         0 *       -99 * 0.9578682 *       -99 *


What happened ?

Also we have no JECUp/Down variables in the data trees.

**Comment by arizzi** [comment]
too bad it wasn't catched in the validation!!

**Comment by degrutto** [comment]
Hi, 
talking with @jpata we where debating if the approach we are using to propagate the uncertainties is really correct.
As we have some of the "interpretation" dependending on btag/pt scale (Higgs choise for both VH and ttH) wheter it really correct to save Jec(Jer)Up(Down) per jet, or instead rather ri-running the whole vhbb.py  with jetScale(JER) Up/Down.... and the same for btag (or maybe just redo at step3). 

I know it is could be an overkill, but I am not sure the way we are currently doing (and the way we did in Run1) is really the correct things to do.
Maybe this can explain some of the over-constraining we were experiencing, for example in run1 we never re-evaluated the highestDiJetpt Higgs candidate with the JER/JEC up or down. We were correctly leaving the acceptance to change with the JER/JEC/btag and the other systematics but never reinterpreting the higgs candidate.

cheers

   Michele

**Comment by jpata** [comment]
@azzurrip @arizzi indeed JEC variations are missing in V13. must be an artifact of the CMG merge that was not caught. Now I cannot investigate as I'm at a conference with poor connection until the end of the week.

**Comment by arizzi** [comment]
there is a new flag to set to True, done in #207

**Comment by degrutto** [comment]
So, JEC uncertainties are fixed, for the JER uncertainty we would need to modify the JetAnalyzer in heppy (if we do not want to duplicate the ntuples).... should I give it a try?

**Comment by arizzi** [comment]
what do you mean? what do you need to change for JER?

**Comment by degrutto** [comment]
I would need to add some leaves to be filled (_JERUP,_JERDOWN).
I believe the best place to do that is in the JetAnalyzer
add a boolean (say addSfiftJER)
for the case
smearJets = True,
   and  shiftJER = 0

so something like (pseudocode)

in https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L376

if (addShiftJER and !shiftJER) 
                  factor = 1.079 + (+1)*0.026...
                  ptscale = max(0.0, (jetpt + (factor-1)*(jetpt-genpt))/jetpt)

                       jet_ptJERUpcorr =                ptscale 

and the same for 
    factor = 1.079 + (-1)*0.026...

**Comment by degrutto** [comment]
ok, code here https://github.com/vhbb/cmssw/tree/addJERshifts_vhbbHeppy74X_MDG/VHbbAnalysis/Heppy

but I believe I rather have to do a PR against colin, but which branch? 745, 747 or 7412?

**Comment by arizzi** [comment]
7 4 12, but I'll make all PR against colin repo (on his request).

Please separate the commits againast central heppy and mark them with
"Heppy: ...comment here"

**Comment by degrutto** [comment]
https://github.com/vhbb/cmssw/pull/219
merged, so we can close this
