### ISSUE TITLE
check met filters

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#216]
https://hypernews.cern.ch/HyperNews/CMS/get/met/419.html

**Comment by silviodonato** [comment]
It seems that the only flag that is missing is HBHENoiseIsoFilter.

The others flags should by covered:
* HBHENoiseFilter loose -> Flag_HBHENoiseFilter
* at least one good PV -> Flag_goodVertices
* eeBadScFilter -> Flag_eeBadScFilter
* CSCTightHalo2015Filter -> Flag_CSCTightHaloFilter

Let me report also the remaining flags in our ntuples

Flag_METFilters

Flag_EcalDeadCellTriggerPrimitiveFilter

Flag_ecalLaserCorrFilter
Flag_hcalLaserEventFilter

Flag_trkPOG_manystripclus53X
Flag_trkPOG_toomanystripclus53X
Flag_trkPOG_logErrorTooManyClusters
Flag_trkPOGFilters

**Comment by arizzi** [comment]
can you guys add it and make a PR?

**Comment by mariadalfonso** [comment]
@arizzi @degrutto
<https://github.com/degrutto>It is safer to re-run the HBHENoiseFilter loose
There has been various problems in the setting of these.

https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_4_12/CMGTools/TTHAnalysis/python/analyzers/hbheAnalyzer.py

**Comment by arizzi** [comment]
someone should import the code and add a NtupleVariable in the output?
@degrutto?

**Comment by degrutto** [comment]
ok see https://github.com/vhbb/cmssw/pull/223

I dediced to copy and keep the hbheAnalyzer in our vhbb directory, but if you want we can create a dependence from the ttH analysis repository

btw the hbheNewFilter flag is 100%eff on 1K events of MC  DY+ll, while the old HBHENoisFilter is only 70% efficient...

**Comment by arizzi** [comment]
for sure no ttH deps, prehaps on the other hand we can promote it to
central heppy!

**Comment by bianchini** [comment]
Hi, let me add here what I found for the other filters we have in the trees.

They are all >99.99% efficient on the signal, but these:
Flag_HBHENoiseFilter.png => 69%  (fixed by Michele)
Flag_METFilters.png => 69% 
Flag_trackingFailureFilter.png => 0%
Flag_trkPOGFilters.png => 91%
Flag_trkPOG_manystripclus53X.png => 91% 
Flag_trkPOG_toomanystripclus53X.png => 95%
Maybe some of them are of no use, but we should check

**Comment by degrutto** [comment]
merged #223
