### ISSUE TITLE
check id and iso of ele and muons we use for leptons jet cleaning

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#229]

**Comment by degrutto** [comment]
see here
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/LeptonAnalyzer.py#L557

for ele: rho dR0.3
for mu: dBeta dR0.4 

and 0.40% as cut

**Comment by degrutto** [comment]
change also
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/analyzers/objects/LeptonAnalyzer.py#L575 in dBeta

**Comment by bianchini** [comment]
fixed in this commit:
5e2291068902f9c9bdadf9f1b1d461415f8ff000

**Comment by arizzi** [comment]
#220 fixes this right?

**Comment by degrutto** [comment]
Right
