### ISSUE TITLE
Check JECs for data

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#230]

**Comment by degrutto** [comment]
for data I uploaded this 74X_dataRun2_reMiniAOD_v0...
as they are suggested (still) here
https://twiki.cern.ch/twiki/bin/viewauth/CMS/JECDataMC#Recommended_for_Data

sorry probably I did not change vhbb_data.py :(

**Comment by degrutto** [comment]
no, it seems it is already ok

https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/test/vhbb.py#L241

**Comment by arizzi** [comment]
is this the same as what used in miniAODV2?

**Comment by degrutto** [comment]
as far as I undestand 

- yes for 05Oct2015 
https://cmsweb.cern.ch/das/request?input=config%20dataset%3D/MET/Run2015D-05Oct2015-v1/MINIAOD&instance=prod/global&idx=0&limit=10

- while 2015DPromptRecov4 (most of the data) uses
74X_dataRun2_Prompt_v4
https://cmsweb.cern.ch/das/request?input=config%20dataset%3D/MET/Run2015D-PromptReco-v4/MINIAOD&instance=prod/global&idx=0&limit=10

which is not listed here 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions

so I do not know, maybe we should ask Gianluca ?

**Comment by arizzi** [comment]
we go with what we have assuming is ok

**Comment by degrutto** [comment]
yes, if we rerun the JEC we use the correct ones, if we do not the ones in the miniAODv2 
are the latest one to use.. so either way we should be ok
