### ISSUE TITLE
Add Jet_rawPtSmaeared

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#244]
In the regression is useful to use the Jet_pt before the JEC.
So far we are using the Jet_rawPt both in data and in MC, but it is wrong: in MC the resolution of Jet_rawPt is better than Jet_pt because of it is not smeared.

To avoid this problem we should add the variable Jet_rawPtSmaeared in MC.

Maybe it would be even better to rename the variable:
in data:
- keep Jet_rawPt

in MC:
- rename Jet_rawPt -> Jet_rawPtUnsmeared
- add Jet_rawPt (ie. Jet_rawPt *with the smearing*).

In this way we expect to have an agreement data/MC for the variable Jet_rawPt.

**Comment by arizzi** [comment]
any PR ?

**Comment by silviodonato** [comment]
#316 closes it.
In any case, now we have Jet_corr both in data and in MC and we can use it in the regression.
