### ISSUE TITLE
Add triggering MVA for electrons

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#249]
Add triggering MVA following here:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2#Recipes_for_7_4_12_Spring15_MVA

**Comment by jpata** [comment]
I'm working on this.

**Comment by jpata** [comment]
@arizzi @cbernet I see that there is already some ele MVA id stuff done here: https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/physicsobjects/Electron.py#L174

via direct TMVA xml files in https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/physicsutils/ElectronMVAID.py#L4

The current EGamma recipe [1] seems to rely on CMSSW modules, which can be added to the preprocessor and then produce ValueMaps for the id cuts corresponding to electrons.

Can you tell me if we prefer the official recipe or keep the custom BDT xml files and working points?

[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2#Recipes_and_implementation

**Comment by bianchini** [comment]
Done my Christian & Joosep
