### ISSUE TITLE
TT+jets lhe variables empty

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#25]
for the TT+jets sample, the lheHT, lheN*, lheV_pt variables are all 0 at least in one file (tree_1.root)

**Comment by arizzi** [comment]
I guess that is not a MG sample

**Comment by degrutto** [comment]
the variabales show be there for a Madgraph sample

cheers,

      Michele

**Comment by jpata** [comment]
Indeed, I had assumes without looking that
/TT_Tune4C_13TeV-pythia8-tauola
is madgraph. I tested lheN* on some
/TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola
and it was fine.
