### ISSUE TITLE
jets for MET correction

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#253]
@bianchini
We might want to check which jets we use for correcting the MET.

In the ttH sync we find (**FIXME** add proper reference once known) 
~~~
Cut values as in PhysicsTools/PatUtils/python/patPFMETCorrections_cff.py
// The jets as provided by miniAOD 
pat::Jet jet = ...;
// Requirement 1 on uncorrected pt > 10 GeV 
jet.correctedJet("Uncorrected").pt() > 10.
// Requirement 2 on electromagnetic energy fraction < 0.9 
(jet.isPFJet() && jet.emEnergyFraction() < 0.9) || (jet.isPFJet() && jet.neutralEmEnergyFraction() + jet.chargedEmEnergyFraction() < 0.9)
// Jets can be pre-selected with abs(eta) < 5.4, as there are no jet energy corrections provided outside this range, so nothing to be propagated to MET
~~~
whereas currently we are doing Type1 with all miniAOD jets and JER with `cleanJetsAll` with some tighter ID and lepton cleaning reqs.

**Comment by bianchini** [comment]
Still unclear to me what is the recipe. Anyway, Michele and I switched off the JER smearing propagation to type1 MET until we have a recipe. It's not ideal but we can go on with that until we make V21 with the latest JEC. Let's update https://github.com/vhbb/cmssw/issues/292 with this extra check and close this issue..

**Comment by degrutto** [comment]
ok, closing
(the prescription is still not to use JER smearing for type-1 MET)
