### ISSUE TITLE
PU weight update

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#256]
A new pileup recipe is available:
https://twiki.cern.ch/twiki/bin/view/CMS/PileupJSONFileforData#2015_Pileup_JSON_Files

**Comment by bianchini** [comment]
Maybe we can close it as well, given that Andrea is working on it: https://github.com/vhbb/cmssw/issues/328 ?

**Comment by arizzi** [comment]
PR in few minutes

**Comment by arizzi** [comment]
#347
