### ISSUE TITLE
MET smearing

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#257]
Need to understand what is the recommended way to propagate JER to MET.

**Comment by arizzi** [comment]
did you figure something about this?

**Comment by degrutto** [comment]
Hi,
To me it seems this is already done in heppy,
see

https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L437

and 

https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/PhysicsTools/Heppy/python/analyzers/objects/METAnalyzer.py#L189


Now the question if that is the recommended presciption
I just asked again to @mariadalfonso and she is saying in principle we never recover for low pt jets like that and that the recommendation is not to do that
(but just consider the JER band in the MET uncertainty tool...)

we should do
METAna. applyJetSmearing = False

probably....

**Comment by degrutto** [comment]
so, the recommendation is to not use the jet smeared for JER 

#311

if you do not have objection we can merge that

**Comment by degrutto** [comment]
actually one thing it maybe worth considering is the recoil correction... 
but we do not have the parameters centrally...

https://twiki.cern.ch/twiki/bin/view/CMS/MissingETRun2RecoilCorrection

**Comment by arizzi** [comment]
so? are we done on this or is there something pending? 
close? move to V21? still open for V20?

**Comment by degrutto** [comment]
Yes,
the MET group suggests not to propagate the JER jet emearing to MET, but just considere the systematics band (and we do save that using the METUnc tool), 
so we are fine
