### ISSUE TITLE
Add JER/JEC propagation to regression 

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#272]
Hello,

we need to add here
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/python/JetRegression.py

the effect of JER/JEC to the regression,
and in general think if there are other systematics to propagate to the regressed pt

**Comment by bianchini** [comment]
Seems the same issue as https://github.com/vhbb/cmssw/issues/288.. can we close it, Michele?

**Comment by degrutto** [comment]
Yes, let's follow on #288
