### ISSUE TITLE
save events with Jep_pt==1 and pt>200 (for very boosted signal)

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#274]
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L451
something like 

if event.Vtype < 0 and not ( sum(x.pt() > 30 for x in event.jetsForHiggs) >= 4 or sum(x.pt() for x in event.jetsForHiggs[:4]) > 160 )  or len(getattr(event, "ak08"))>0

**Comment by arizzi** [comment]
not needed as the sum pt > 160 is already a looser requirement

**Comment by degrutto** [comment]
ok, I see, thanks

**Comment by degrutto** [comment]
maybe better solution to keep events with very high boosted jets is to modify line 
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L449
to allow the case we have one ak4 jets but with very high pt

	if not   len(event.jetsForHiggs) >= 2 : # and event.jetsForHiggs[1] > 20.) : # or(len(event.cleanJets) == 1 and event.cleanJets[0] > ssThreshold ) ) :

**Comment by degrutto** [comment]
see https://github.com/vhbb/cmssw/pull/275
