### ISSUE TITLE
Add JER/JES related stuff

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#28]
We should add the information to handle JER/JES uncertainty.

**Comment by arizzi** [comment]
@jpata

**Comment by jpata** [comment]
Took a while but we have now JES uncertainties (Summer13) attached to the jets in PR #67, also needed #68.

**Comment by arizzi** [comment]
@jpata  I close this too, right? We checked that JER is already implemented by Heppy

**Comment by jpata** [comment]
right.
