### ISSUE TITLE
Regression in ntuples

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#288]
If we really want to use the regression in the ntuples, I think we need the following change:
- remove at least the chHEF, neHEF, and chMult from the training because there is a bad data/MC agreement in those variables.
- add also the JES/JER systematics on the regressed variables.

**Comment by arizzi** [comment]
@cvernier @degrutto any action here?

**Comment by cvernier** [comment]
I'll commit the new weights as soon as we decide which set of weights to use. David has just circulated slides with studies and a proposal.

**Comment by arizzi** [comment]
@cvernier ping

**Comment by arizzi** [comment]
@silviodonato can you check if #340 is enough or if there is something missing of what you recommended?

**Comment by silviodonato** [comment]
I see that the charged multiplicity is still used. In my plots it appears that it is badly simulated:
http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V15Feb2016/Stacks_expertAllnominal_v0.0.0_CRs/CR_TTbarTight_Jet_chMult0_125.png
http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V15Feb2016/Stacks_expertAllnominal_v0.0.0_CRs/CR_TTbarTight_Jet_chMult1_125.png

The other point was about the JES/JER. In order to use the regression in the analysis we need the JES/JER systematics!

**Comment by arizzi** [comment]
concerning charge multiplicity I'd say this is the effect of tracking hit inefficiency + CCC... it should be cured in 8.0.X (but not 76X).
JES JER means we need to run the regression also with scaled up/down JES/JER right? so we need additional instances and store what... mH, ptH ?

**Comment by silviodonato** [comment]
Yes, we need to run with Jet_pt JER/JES up/down as input into the regression.

All regressed variables should have the syst:
- Jet_pt_reg

- HCSV_reg_pt
- HCSV_reg_mass
- HCSV_reg_eta
- HCSV_reg_phi

- HCSV_reg_pt
- HCSV_reg_mass
- HCSV_reg_eta
- HCSV_reg_phi

**Comment by bianchini** [comment]
Ciao, do you think that any of you can do it by today?

**Comment by bianchini** [comment]
Ok, I think I know I to do it. If nobody is planning to do it, I will give it a try right now!

**Comment by bianchini** [comment]
Should be done in https://github.com/vhbb/cmssw/pull/350. We can close

**Comment by silviodonato** [comment]
Thanks! I've just tested it and it works properly.

**Comment by azzurrip** [comment]
Need to have a regression trained with 76X inputs.
@cvernier hopefully can produce fall15 weights 
Only  a small A20 ttbar tree is available for the moment ...

**Comment by degrutto** [comment]
@azzurrip  this is true but the JEC are not final (they are still the same as 74X afaik), so I am not sure how to proceed

**Comment by azzurrip** [comment]
Ok but JEC is only in one of the regression inputs.
Anyhow better to align the other inputs with 76X distributions
before a big production, otherwise we won’t know how to understand performances.


On 05 Feb 2016, at 17:35, michele de gruttola <notifications@github.com<mailto:notifications@github.com>> wrote:


@azzurrip<https://github.com/azzurrip> this is true but the JEC are not final (they are still the same as 74X afaik), so I am not sure how to proceed

**Comment by cvernier** [comment]
Retrained using ~100k jets from TT in v20 PR353
[regressed_Mass_ZH125_v20_ttbar_genJet_highPt.pdf](https://github.com/vhbb/cmssw/files/119609/regressed_Mass_ZH125_v20_ttbar_genJet_highPt.pdf)
[regressed_Mass_ZH125_v20_ttbar_genJet.pdf](https://github.com/vhbb/cmssw/files/119608/regressed_Mass_ZH125_v20_ttbar_genJet.pdf)
