### ISSUE TITLE
New JER

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#292]
Make sure we have this PR merged by Colin:
https://github.com/CERN-PH-CMG/cmg-cmssw/pull/602/files

**Comment by arizzi** [comment]
let's wait cmg update otherwise we conflict

**Comment by bianchini** [comment]
We should have a clear recipe on which jets to use for the JER smearing to MET. Currently it's cleanJetsAll, we should use the same jets used for type1 MET correction:
************************************************************************
Cut values as in PhysicsTools/PatUtils/python/patPFMETCorrections_cff.py
// The jets as provided by miniAOD 
pat::Jet jet = ...;
// Requirement 1 on uncorrected pt > 10 GeV 
jet.correctedJet("Uncorrected").pt() > 10.
// Requirement 2 on electromagnetic energy fraction < 0.9 
(jet.isPFJet() && jet.emEnergyFraction() < 0.9) || (jet.isPFJet() && jet.neutralEmEnergyFraction() + jet.chargedEmEnergyFraction() < 0.9)
// Jets can be pre-selected with abs(eta) < 5.4, as there are no jet energy corrections provided outside this range, so nothing to be propagated to MET

**Comment by bianchini** [comment]
Done with https://github.com/vhbb/cmssw/pull/378
