### ISSUE TITLE
MET significance and metNoPU_pt

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#298]
We should add the MET significance, and fill metNoPU_pt properly (metNoPU_pt is identical to met_pt)

**Comment by arizzi** [comment]
what is metNOPU supposed to be?

**Comment by degrutto** [comment]
it is not supported anymore... we should just remove it, I'll take care of it

**Comment by arizzi** [comment]
hold on, I will remove or we conflict

**Comment by degrutto** [comment]
ok

**Comment by arizzi** [comment]
#307
