### ISSUE TITLE
Primary vertices

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#300]
At the moment we are saving the following variables:
- primaryVertices_Rho
- primaryVertices_isFake
- primaryVertices_ndof
- primaryVertices_x
- primaryVertices_y
- primaryVertices_z

I suggest to add a variable to measure the hardness of pile-up collisions, like the sum of squared pT or the score used to sort the primary vertices.

I think also that we could remove some variables almost useless (eg. x and y).

**Comment by arizzi** [comment]
@bortigno do you need x and y ? I remember you asked to have the positions in the past

**Comment by bortigno** [comment]
I think they could be useful for a higgs / double b-tagging study. thank you.
