### ISSUE TITLE
Event gen level classification

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#305]
Does someone implemented the gen event classification in the new ntuples?

https://twiki.cern.ch/twiki/bin/viewauth/CMS/VHiggsBBCodeUtils#Gen_level_classification_NEW

**Comment by bianchini** [comment]
Check if ttCls does the job. I have the impression that it works: it loops over all gen Jets pT>20 |eta|<2.4, removes those from the top decay [fine], checks the matching to B/C hadrons and assigns every event to an exadecimal number..

**Comment by bianchini** [comment]
Ok Silvio, I checked: you can already use:
TCut Vbb = "ttCls>=53 & ttCls<=55"
TCut Vb = "ttCls>=51 & ttCls<=52"
TCut Vcc = "ttCls>=41 & ttCls<=45"
TCut Vudsg = "ttCls<41"
Twiki updated.

**Comment by silviodonato** [comment]
Good news! It speeds up the code :-)

**Comment by arizzi** [comment]
can we close this then?
