### ISSUE TITLE
How to use the LHE_weights_scale

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#327]
@perrozzi @arizzi 
Ciao, if you remember we had added LHE_weights_scale for the muR/muF variations.
Question 1: what about PDFs? I think we still don't want to dump all possible PDFs. Maybe we can leave i for later.
Question 2: the muR/muF variations are often renormalised in a way that they don't change the inclusive cross sections, for example if I don't want to change the inclusive xsection that is known to a better order. But at the moment we don't have a way to compute Sum[weights] over all events. I guess we can add histograms like:
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L55
to get the correct nornalisation. What you think?

**Comment by arizzi** [comment]
in Run1 we were storing several such histos, so I've nothing against that

**Comment by bianchini** [comment]
Good, I am implementing them...

**Comment by bianchini** [comment]
Should be done with https://github.com/vhbb/cmssw/pull/331

**Comment by perrozzi** [comment]
Ciao, concerning question 1 I would say that nnpdf30 is sufficient (though it's 100 numbers).
Concerning question 2 there are very good theoretical arguments NOT to renormalize the sum of weights after scale variations, and include these variations as part of the systematics.
we can discuss more about it if you want

**Comment by bianchini** [comment]
Ciao, for the moment I put the 6 up/down scale variations, with their TH1 counter, and 2 NNPDF variations, with the counter. I took the two that Marco et al. found the largest in tt+jets, so it's more a placeholder at the moment (no idea why and which they are). If we need the full NNPDF fr some samples, we may have a special run, I guess. Anyway, if we drop DscardedJets we are likely to save 100 floats or more per event.
