### ISSUE TITLE
puWeight_up/down is missing

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#328]
We should  puWeight_up/down in the ntuples to take into account the PU reweighing systematic.

**Comment by bianchini** [comment]
Ciao, ins't it better to apply the puWeight later, once we have the latest&greatest json file? We have already a macro for that..

**Comment by arizzi** [comment]
the PU in this MC is almost exactly like data, anyhow I'm updating the files right now...

**Comment by arizzi** [comment]
#347
