### ISSUE TITLE
Split by Higgs decay modes: VH_hzg ?

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#332]
If we have to split by Higgs decay modes, I think we don't have hzg at the moment:
event.genHiggsDecayMode = abs(  event.genHiggsBoson.daughter(0).pdgId() if event.genHiggsBoson.numberOfDaughters() >= 1 else 0)
Should use some logic there.

**Comment by arizzi** [comment]
how about 
event.genHiggsDecayMode+ = abs( event.genHiggsBoson.daughter(1).pdgId() if event.genHiggsBoson.numberOfDaughters() >= 2 else 0) * 10000

**Comment by arizzi** [comment]
sorry I meant 
event.genHiggsDecayMode+ = abs( event.genHiggsBoson.daughter(1).pdgId() if event.genHiggsBoson.numberOfDaughters() >= 2 and  abs( event.genHiggsBoson.daughter(1).pdgId() ) != abs( event.genHiggsBoson.daughter(0).pdgId())    else 0) * 10000

**Comment by bianchini** [comment]
Yes, that should work. I will test against a H->others sample to see if that works.

**Comment by arizzi** [comment]
#344
