### ISSUE TITLE
Check MVA ele duplication

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#335]
I'm guessing we have the same MVA computed from (CMG/central) Heppy  and from preprocessor @jpata can you cross check?

**Comment by bianchini** [comment]
@veelken: Ciao Christian, maybe you can help here... there seems to be some duplication of the electronMVA id between heppy and what is in vhbb. Can you quickly check that they are compatible? Thanks!

**Comment by bianchini** [comment]
I would say we can close.
Our ID is fine. We essentially implement the full-framework recipe in our preprocessor. We can always switch to the mvaID stored in the miniAOD once it's stable.

**Comment by perrozzi** [comment]
just to make sure, this can be closed right?

**Comment by veelken** [comment]
I agree this PR can be closed.
