### ISSUE TITLE
metNoHF

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#363]
What shall we do with this? 
From https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/1661/1.html I see that
"The recommendation is to use the golden JSON and the met w/full detector"
I'd rather recompute slimmedMETsNoHF. 
Does anybody have an implementation? I tried to modifi combined_cmssw using PhysicsTools/PatAlgos/test/corMETFromMiniAOD.py
but miserably failed.

**Comment by arizzi** [comment]
how about "let's stick to the recommendation" ?
:-)

**Comment by bianchini** [comment]
uhm.. I would not lose 400pb just for this..

**Comment by bianchini** [comment]
Ciao, given also https://hypernews.cern.ch/HyperNews/CMS/get/met/448.html I'd say to forget about metNoHF+silver for Moriond and use fullMET+golden. Do you agree? We can then close this issue. 

About JER: we already removed JER propagation to MET: https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/test/vhbb.py#L240, so we are fine. But we need the good JER scale factors (still using 8TeV values)!

**Comment by arizzi** [comment]
anyhow I added silver json flag

**Comment by bianchini** [comment]
Sounds good. Close
