### ISSUE TITLE
protect div by zero

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#365]
https://cmsweb.cern.ch/scheddmon/066/cms1756/160210_081323:arizzi_crab_VHBB_HEPPY_V20_001_SingleMuon__Run2015D-16Dec2015-v1/job_out.578.8.txt

**Comment by bianchini** [comment]
https://github.com/bianchini/cmssw/commit/56b9e49ec2c9be97c7e2cfb5cb722fb07222b192 should do the job. But the problem is in Lepton.py (Heppy). Chained to my previous PR.

**Comment by arizzi** [comment]
#362
