### ISSUE TITLE
MET shifted issue

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#369]
I've spotted in the file (V15)
/store/user/arizzi/VHBBHeppyV14/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/VHBB_HEPPY_V14_QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/151025_083609/0000/tree_12.root

tree->Show(718)

 met_pt          = 156.356
 met_shifted_JetEnDown_pt = 130.645
 met_shifted_JetEnUp_pt = 131.038
 met_shifted_MuonEnDown_pt = 150.726
 met_shifted_MuonEnUp_pt = 111.195
 met_shifted_ElectronEnDown_pt = 129.999
 met_shifted_ElectronEnUp_pt = 131.638
 met_shifted_TauEnDown_pt = 131.377
 met_shifted_TauEnUp_pt = 130.263
 met_shifted_UnclusteredEnDown_pt = 130.319
 met_shifted_UnclusteredEnUp_pt = 131.402
 met_shifted_JetResDown_pt = 130.818
 met_shifted_JetResUp_pt = 130.818

I expected that the met_pt was between the met_shifted_*Up/Down_pt.
Here we have for instance:
 met_pt          = 156.356
 met_shifted_JetEnDown_pt = 130.645
 met_shifted_JetEnUp_pt = 131.038

To be checked.

**Comment by perrozzi** [comment]
(ciao, naively speaking the met is a vectorial sum over the full event, so is not obvious to me that the jec up/down have a "linear" effect)

**Comment by silviodonato** [comment]
that is true,
but looking at the reported events it is curios that all shifted MET are around ~ 130 GeV,  but met_pt = 156.356

**Comment by degrutto** [comment]
Hi Silvio, I believe this is due to the fact in V14 we had the jer smearing propagated to met (I switched it off in v20)... can you plot for those ebents the jet_pt, jet_raw, jet_jerUp/down?

**Comment by silviodonato** [comment]
This was an event of fakeQCD with a jet of 57 GeV measured as 209 GeV. So the JER corrections have a large effect and they can explain the problem.

 Jet_pt          = 209.784, 
                  45.7247, 43.9536

 Jet_rawPt       = 183.167, 
                  42.1796, 41.4892

 Jet_mcPt        = 57.7131, 
                  48.5465, 41.2616

 Jet_corr_JECUp  = 1.08156, 
                  1.11155, 1.07503
 Jet_corr_JECDown = 1.0595, 
                  1.06859, 1.03208
 Jet_corr        = 1.07053, 
                  1.09007, 1.05355
 Jet_corr_JERUp  = 1.08962, 
                  0.992908, 1.00712
 Jet_corr_JERDown = 1.0501, 
                  0.996035, 1.00398
 Jet_corr_JER    = 1.06986, 
                  0.994471, 1.00555

**Comment by silviodonato** [comment]
@degrutto if you think this problem is already solved in V20, please close the issues.

**Comment by degrutto** [comment]
;-) thanks for the check, I believe the problem is indeed well understood and cured in v20 ;-)
