### ISSUE TITLE
ext4 of DYJetsToLL_FxFx

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#374]
@perrozzi @benjaminkreis
Ciao, I have seen from https://hypernews.cern.ch/HyperNews/CMS/get/higgs/1729/1/1.html that there is this sample:
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1/MINIAODSIM
with 120M events. Can we add it to datasets_MCRUN2_25ns_RunIIFall15MiniAODv2-PU25nsData2015v1_76X.txt?

**Comment by benjaminkreis** [comment]
@bianchini, this is added in PR #379

**Comment by bianchini** [comment]
Thanks Ben!
