### ISSUE TITLE
PU Jet ID variables

### ISSUE THREAD

**Issue by scooperstein** [vhbb/cmssw#38]
I am unable to find some of the PU Jet ID variables in the current Step 2 ntuples, maybe I missed them. Beta and betastar, which appear to have the best discriminating power, are of particular interest. If these variables are not currently included, it would be very useful to implement them.

Cheers,
Stephane

**Comment by arizzi** [comment]
can you add them and make a PR in the next 24-48h ?

**Comment by capalmer85** [comment]
In the next 48-72, yes.  Today, neither Stephane nor I will be able to look
into this.

**Comment by arizzi** [comment]
hi guys, any update here? I did not see it coming in 72h ... then it was
easter... :-)

**Comment by capalmer85** [comment]
Hi Andrea,  Sorry.  I got really sick at the end of last week and I
completely forgot.  Please don't wait on us for the next production if you
want to start right away.  I'll try to get this in this week.  Thanks for
the followup.

**Comment by arizzi** [comment]
hi guys any news? can you please add this stuff?
please start from vhbbHeppy743 (and a CMSSW 743 release area)

**Comment by arizzi** [comment]
hi guys, we are closing V12 in few days... any luck with this?

**Comment by scooperstein** [comment]
Hi Andrea,

Sorry that this is not yet taken care of. I did some digging with Michele, and unfortunately these variables are not currently stored in the miniAOD, so we don't directly have access to the these inputs for the Pileup Jet Id discriminator, just the output. We can re-calculate beta and betastar ourselves, but I have not yet had the chance to implement it.  I will try to do so before the V12 campaign, but I have upcoming deadlines with my Tracking work and I may not get to it in time. These variables would be useful if we want to validate and/or tweak the pile-up jet ID ourselves, but they are certainly not essential to have in the V12 campaign if it can't happen in time.

Cheers,
Stephane

**Comment by arizzi** [comment]
should we try to have this in V13?

**Comment by capalmer85** [comment]
When do you want to start the full campaign?  If it is some time next week,
I'll give it shot.

Just so you know, Stephane looked into this some time ago with Michele and
they found that the variables can't be easily extracted but that they must
be recomputed.  I can do this if the track collection with jet association
variables are available in miniaod.  Do you happen to know if that is the
case?

**Comment by arizzi** [comment]
can you list the variables you need? you definitely at least 1 week time

**Comment by capalmer85** [comment]
Minimally we need:

beta star (classic)
track pt weighted dR

The algorithms are in computeIdVariables in
http://cmslxr.fnal.gov/source/RecoJets/JetProducers/src/PileupJetIdAlgo.cc?v=CMSSW_7_4_0_pre2

Can we use this code exactly with miniAOD?  This function only needs
const reco::Jet * jet
const reco::Vertex * vtx,
(the other args are just numbers)
Do we have the constituent particles to the jets at miniAOD level?

**Comment by capalmer85** [comment]
I've been digging through the code a little bit and I think we want
the inputs to this puMva:
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/PhysicsTools/Heppy/python/physicsobjects/Jet.py#L81

I couldn't get any deeper than this.  Do you know what
"userFloat(label)" does under the hood?  I can see it returns the mva
value and then checks the id level below, but is that mva value saved
in the jet or taken from a bdt xml?

**Comment by degrutto** [comment]
Hi, I'd say this is not critical for v14, correct?

**Comment by capalmer85** [comment]
Yes, not critical.
