### ISSUE TITLE
MET in 76X

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#381]
In the JetMET hyper-news, the POG reported the new recipes for the MET reconstruction [1]. 

The only things that we have to check is:
- to use the JEC "Fall15_25nsV2" in 76X (I think we are already using it)
- to use the new filters [2]. The changes are: 
 - Flag_CSCTightHalo2015Filter instead of Flag_CSCTightHaloFilter (currently Flag_CSCTightHalo2015Filter **is missing in V20**)
 - Flag_EcalDeadCellTriggerPrimitiveFilter (it was wrong in 74X, it was already in V20)
 - as far as I understood, in 76X we can pick directly all MET filters from the MINIAOD instead of producing them by ourself. I'm referring to Flag_HBHENoiseFilter and Flag_HBHENoiseIsoFilter 

[1]: https://hypernews.cern.ch/HyperNews/CMS/get/met/448.html
[2]: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#MiniAOD_76X_v2_produced_with_the

**Comment by bianchini** [comment]
Ciao,
see: https://github.com/bianchini/cmssw/commit/cb1addc8e035cf5b5d55e8480d11fbd81c834291 for the missing filters: is it enought?
Yes, we are using Fall15 V2

**Comment by silviodonato** [comment]
Ciao,
it would be better also to take
- Flag_HBHENoiseFilter
- Flag_HBHENoiseIsoFilter
- Flag_EcalDeadCellTriggerPrimitiveFilter, 
directly from the MINIAOD.
Maybe we are already doing it for Flag_EcalDeadCellTriggerPrimitiveFilter.

Thanks, Silvio.

**Comment by arizzi** [comment]
can you please check? I'd like to send V21 today...

**Comment by bianchini** [comment]
We alreadu have them from central heppy. Please check:
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/PhysicsTools/Heppy/python/analyzers/core/TriggerBitAnalyzer.py#L125
I see all of them.

**Comment by degrutto** [comment]
@arizzi: to start the v21 we need some fixes to the regression application (for wahtever new weight files we use), I'll do a PR and than let's see which weight files to use

**Comment by silviodonato** [comment]
Great! So bianchini@cb1addc closes the issue.
