### ISSUE TITLE
Bug in PU weight Down

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#386]
I've just spotted a bug.
PU weight down is always identical to PU weight up, even in H21!! 

It looks like PU weight up is right, but PU weights down is overridden by PU weight up.

**Comment by arizzi** [comment]
well we can symmetrize, anyhow if you spot the bug in the code please fix

**Comment by silviodonato** [comment]
https://github.com/vhbb/cmssw/pull/387 close it
