### ISSUE TITLE
76X Jet pileup id ? 

### ISSUE THREAD

**Issue by azzurrip** [vhbb/cmssw#389]
Do we want to make sure to use 76X pu jet-id  ?
https://hypernews.cern.ch/HyperNews/CMS/get/jet-algorithms/383.html
https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetID#Information_for_13_TeV_data_anal
https://indico.cern.ch/event/502737/contribution/3/attachments/1234291/1811331/PileupJetID_76X.pdf
it should be much better than using the previous version. 
Guess this should go in central heppy right ?

**Comment by bianchini** [comment]
Ciao, any news about that?
Can anybody look at it? We need the good pileup jet ID, because we do use it.

**Comment by arizzi** [comment]
I can have a look, would you prefer to replace the selection based on the new one or just add one more flag for puId76 ?

the example given foresee also jet-correction before the new ID but I think we can avoid that (as it would make the changes more invasive and more error prone)... in the end a 5% wrong pT should not affect much the PU ID ... isn't it? I mean the resolution is larger than the shift in response due to updated JECs

**Comment by bianchini** [comment]
ciao Andrea, great, thanks! Ideally, we would like to update the Higgs jet selection to this new jetID, and add puId76 for all the jets.. 
I am fine with not changing the jet energy before.. I am also puzzled, I thought this ID was working at the level of pfcandidates..

**Comment by azzurrip** [comment]
Yes great if we can replace it ! I think the previous one is really not working well (and limited to central jets). For low pT jets (say around 30 GeV or lower) the value of the pT is important to classify properly the jet  (based on the internal composition). For this I guess is important not to use the raw pT as it can be significantly smaller than the corrected pT.

**Comment by arizzi** [comment]
is not raw anyhow, at most it is " Old JECs"
Il 02/mar/2016 10:16, "azzurrip" <notifications@github.com> ha scritto:

**Comment by azzurrip** [comment]
Ok fine then

**Comment by arizzi** [comment]
btw this will require migration to 763p2

**Comment by bianchini** [comment]
Ok. I am also struggling with the EGamma energy corrections that are also based on 763p2...
Shall we give up?

**Comment by arizzi** [comment]
#398 should implement the new PU ID

**Comment by bianchini** [comment]
@azzurrip: Paolo do you think we can close this issue? Is the new puId fine?

**Comment by azzurrip** [comment]
Yes very fine.

On 15 Mar 2016, at 15:30, bianchini <notifications@github.com<mailto:notifications@github.com>> wrote:


@azzurrip<https://github.com/azzurrip>: Paolo do you think we can close this issue? Is the new puId fine?
