### ISSUE TITLE
DY with Mll 10-50

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#390]
@benjaminkreis @perrozzi 
Ciao, do we have samples with Mll<50 GeV? The ttbar CR reads:
"Mll not in [75,110]"
so we cannot ignore low mass DY for this region.

**Comment by benjaminkreis** [comment]
@bianchini @perrozzi 

DAS is down right now, but by searching around McM(*), I expect we should be able to find:
/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/MINIAODSIM
/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/MINIAODSIM

https://cms-pdmv.cern.ch/mcm/requests?dataset_name=DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8&page=0&shown=285212799

**Comment by bianchini** [comment]
Thanks, Ben! It's unfortunate that we don't have MG5 samples to be used together with the M-50 ones.
Could you please add at least these ones into https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/test/crab/datasets_MCRUN2_25ns_RunIISpring15MiniAODv2.txt ? I am not sre about the ext, and if we need all of them or only some. 
Thanks.

**Comment by benjaminkreis** [comment]
Hi Lorenzo,

Looking again with DAS back up, I also found: 
/DYJetsToLL_M-5to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM

and the same in HT bins:
/DYJetsToLL_M-5to50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM

Do you want to go with the madgraph instead?  Inclusive or HT binned?

Ben

**Comment by bianchini** [comment]
Hi Ben, these are 74X samples.. do we have them also in 76X?
About the samples, naively I'd say all of them.
@perrozzi: is that ok?

**Comment by benjaminkreis** [comment]
Oops I see.  The dataset list file you mentioned above is the 74x one.

For madgraph in 76X, I see:
/DYJetsToLL_M-5to50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
/DYJetsToLL_M-5to50_HT-600toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

There are also inclusive ones in progress.

Ben

**Comment by benjaminkreis** [comment]
PR #394

**Comment by perrozzi** [comment]
ciao, sorry to come late, I agree with the need to add and I see that they have already merged, thanks
