### ISSUE TITLE
Jet_corr in regression has to be fixed

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#393]
My current understanding is (mixing heppy and vhbb names):

Jet_rawPt = j.rawFactor() * Jet_pt
[https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L440]

Jet_pt = Jet_rawPt * Jet_corr * Jet_corr_JER

hence:
Jet_corr = 1 /  j.rawFactor() / Jet_corr_JER

Can you confirm?

Then, from https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/python/JetRegression.py#L70 I see that what is called "Jet_corr" in the BDT training is actually filled with j.rawFactor(), but evaluated with 1/j.rawFactor()/Jet_corr_JER..

@cvernier, @degrutto : maybe it's just me slow at the end of the day, but can you double check?

**Comment by degrutto** [comment]
Hi @bianchini 
(btw, the confusion is that _corr should read _corrJEC! )
so I confirm

Jet_pt = Jet_rawPt * Jet_corr * Jet_corr_JER  see [*]

and also
rawFactor = Jet_rawPt / Jet_pt (corr JER + JEC) =1/ ( jet_corr * jet_corrJER)

so 
jet_corr (only JEC) = (1/ rawFactor)  / jet_corrJER !

so L70 should be changed to be 
 self.Jet_corr[0] = (1/ j.rawFactor()/ jet_corrJER) / pt_corr

but why not  even simpler

self.Jet_corr[0] = ( jet_corr) / pt_corr  ?



[*]
 tree->Scan("Jet_rawPt:Jet_corr:Jet_corr_JER:Jet_pt:Jet_rawPt*Jet_corr*Jet_corr_JER")
***********************************************************************************
*    Row   * Instance * Jet_rawPt *  Jet_corr * Jet_corr_ *    Jet_pt * Jet_rawPt *
***********************************************************************************
*        0 *        0 * 84.189796 * 1.0582933 * 0.9989578 * 89.004646 * 89.004650 *
*        0 *        1 * 65.142646 * 1.0596181 * 1.0029003 * 69.226524 *  69.22653 *
*        0 *        2 * 60.819320 * 1.0655020 * 0.9960448 * 64.546798 * 64.546802 *
*        0 *        3 * 33.105632 * 1.1408617 * 1.0097552 * 38.137394 * 38.137395 *
*        0 *        4 * 32.458133 * 1.0737624 * 1.0002510 * 34.861076 * 34.861073 *
*        0 *        5 * 31.620266 * 1.0802620 * 1.0131138 * 34.606121 * 34.606119 *

**Comment by degrutto** [comment]
btw I am lookig at V20, ttbar sample

TFile *_file0 = TFile::Open("/afs/cern.ch/user/d/degrutto/eos/cms/store/group/phys_higgs/hbb/ntuples/V20/user/arizzi/VHBBHeppyV20/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8/VHBB_HEPPY_V20_TT_TuneCUETP8M1_13TeV-amcatnlo-Py8__fall15MAv2-pu25ns15v1_76r2as_v12-v1/160209_171214/0000/tree_185.root")

It seems for pt_reg_JER up and down is not working ....

tree>Scan("Jet_pt:Jet_rawPt:Jet_pt_reg:Jet_pt_reg_corrJECDown:Jet_pt_reg_corrJECUp:Jet_pt_reg_corrJERDown:Jet_pt_reg_corrJERUp")***********************************************************************************************************
*    Row   * Instance *    Jet_pt * Jet_rawPt * Jet_pt_re * Jet_pt_re * Jet_pt_re * Jet_pt_re * Jet_pt_re *
***********************************************************************************************************
*        0 *        0 * 89.004646 * 84.189796 * 99.159065 * 97.201408 * 99.159065 * 99.159065 * 99.159065 *
*        0 *        1 * 69.226524 * 65.142646 * 76.216239 * 70.479888 * 76.216239 * 76.216239 * 76.216239 *
*        0 *        2 * 64.546798 * 60.819320 * 66.319244 * 66.098068 * 66.784019 * 66.319244 * 66.319244 *
*        0 *        3 * 38.137394 * 33.105632 * 42.105236 * 41.232669 * 42.225109 * 42.105236 * 42.105236 *
*        0 *        4 * 34.861076 * 32.458133 * 37.019676 * 35.596744 * 37.788185 * 37.019676 * 37.019676 *
*        0 *        5 * 34.606121 * 31.620266 * 37.758926 * 35.767631 * 39.306823 * 37.014621 * 38.538311 *
*        0 *        6 * 21.295307 * 17.644607 * 30.533784 * 30.533784 * 30.670822 * 30.533784 * 30.533784 *
*        1 *        0 * 89.203117 * 86.533798 * 88.759758 * 88.759758 * 90.265502 * 88.759758 * 88.759758 *
*        1 *        1 * 88.464683 * 85.513298 * 91.131874 * 88.802078 * 91.131874 * 91.131874 * 91.131874 *
*        1 *        2 * 34.510501 * 33.320945 * 38.429451 * 36.507549 * 39.108078 * 38.429451 * 38.429451 *

**Comment by degrutto** [comment]
and the problem is this
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/python/JetRegression.py#L65

ot should be

'corrJER' -> 'corr_JER' !!!

**Comment by arizzi** [comment]
@silviodonato

**Comment by bianchini** [comment]
Ciao, so thinking a bit more:

For the regression I'd use:
 - Jet_pt, i.e. the fully calibrated jets
 - Jet_pt/Jet_rawPt (==Jet_corr*Jet_corr_JER), i.e. what we need to apply to raw jets to get fully calibrated ones.

Then, the systematic variations correspond to:
 - Jet_pt --> Jet_pt*(Jet_corr_JECUp(Down)/Jet_corr), Jet_pt*(Jet_corr_JERUp(Down)/Jet_corr_JER)
 - Jet_pt/Jet_rawPt --> Jet_corr_JECUp(Down)*Jet_corr_JER, Jet_corr*Jet_corr_JERUp(Down) 

Comments?

**Comment by silviodonato** [comment]
Ciao Lorenzo,
what about to use directly the variables that are filled in the ntuples:
Jet_pt = Jet_rawPt * Jet_corr * Jet_corr_JER ?
Just to avoid any problem...

**Comment by degrutto** [comment]
Hi,

I am not sure I agree

The regression is doing again the calibration as a new JEC (flavour=5),
so you do not want to mix with the JER.

Jet_corr as it is to me is a reasonable variable to give as input as it is the amount of correction form the JEC (only)
Then we correctly treat the jet_pt to be with JER smear for MC
so I would leave as it is but replacing line 70 for systematics with 

self.Jet_corr[0] = j.corr() * pt_corr if "JER" not in analysis else j.corr()


cheers

 Michele

**Comment by bianchini** [comment]
Ok guys, I am happy like this! Michele will make a PR to fix it. I will then close this issue

**Comment by degrutto** [comment]
see https://github.com/vhbb/cmssw/pull/408 this is also containes new weights

**Comment by silviodonato** [comment]
@cvernier @dcurry

**Comment by bianchini** [comment]
Done by https://github.com/vhbb/cmssw/pull/408
