### ISSUE TITLE
HCSV_reg

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#395]
Hello, 
some time ago I implemented all the possible H_reg/HCSV_reg variations for JEC JER up/down.
However we don't really need them, since we already save Jet_pt_reg, Jet_pt_reg_corrJECUp, ...,
so we can always get the shifted Higgs mass by multiplying HCSV_mass by ratios of Jet_pt_reg_*[hJidx].

It's quite some lost CPU everytime we evaluate it:
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L273

Any strong opinion about keeping them? If not I would comment them out.

**Comment by arizzi** [comment]
did you profile it? is it actually slow?

**Comment by bianchini** [comment]
Ciao, no, I have not done it myself, but it's anyway 8 more accesses to the BDT, and each time we regress all jets in the event..

**Comment by bianchini** [comment]
ok.. I am running on a few events and let you know what I see..

**Comment by bianchini** [comment]
Ok. So:
    ncalls  tottime  percall  cumtime  percall filename:lineno(function)    
      13    0.100    0.008    0.830    0.064 VHbbAnalyzer.py:270(doVHRegression)

Without DoVHRegression:   1274811 function calls (1266264 primitive calls) in 82.710 seconds 
With DoVHRegression:        1286529 function calls (1278147 primitive calls) in 82.780 seconds

I guess we can conclude it's not a problem.... then its just about space: I get 3% smaller ROOT file without saving H_reg (100 events): is it worth it?

**Comment by degrutto** [comment]
I would keep them, to make sure all analysts really do the systematics right

**Comment by bianchini** [comment]
Fine for me. I was hoping we could gain some CPU, but I figured out the opposite.
