### ISSUE TITLE
lower pt cut for single jet pass condition

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#403]

**Comment by bianchini** [comment]
Ciao Andrea. 
How low? 
I had a similar idea that we should keep Z+1j doing balancing studies for the regression. In that case, one jet plus one b-tagged jet may do the job. Was this the idea?

**Comment by arizzi** [comment]
I received a request from VZ cross check analysis to lower to 1 pt 170
FatJet

**Comment by bianchini** [comment]
Ok, so not what I had in mind... 
@degrutto @cvernier: we were discussing back in December a good way to validate the regression is through the Z pt balance in Z+1j events, with the jet recoiling against the Z. But we don't have such events in the trees. We could think about 1 jet>20 plus some b-tagging, for example CSVM. What do you think?

**Comment by degrutto** [comment]
Hi,
sorry to comment only now, maybe do that only for two muons/leptons? I'm fraid if we extend to all vType we would accept too many events (for example for QCD)

**Comment by cvernier** [comment]
We could restrict to Vtype=0 (muon) only or include Vtype=1 too.

**Comment by arizzi** [comment]
not doing it as not needed for now.
