### ISSUE TITLE
Using freshly computed eleMVA

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#414]
I realized that we were using the eleMVA ID stored in the miniAOD to decide the Vtype:
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/test/vhbb.py#L293
while we should use the one recomputed according to https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2#Recipes_and_implementation
I checked on a few MC events that the two are similar but not identical.
This way we are consistent with the variables we save in the trees.
Done by https://github.com/vhbb/cmssw/pull/413

**Comment by bianchini** [comment]
Uhm... I am a bit puzzled by this printout we get when running vhbb_combined.py:

MVABin 0 : MethodName = BDT , type == 2 , Load weights file : /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_3_patch2/external/slc6_amd64_gcc493/data/RecoEgamma/ElectronIdentification/data/PHYS14/EIDmva_EB1_5_oldscenario2phys14_BDT.weights.xml
MVABin 1 : MethodName = BDT , type == 2 , Load weights file : /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_3_patch2/external/slc6_amd64_gcc493/data/RecoEgamma/ElectronIdentification/data/PHYS14/EIDmva_EB2_5_oldscenario2phys14_BDT.weights.xml
MVABin 2 : MethodName = BDT , type == 2 , Load weights file : /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_3_patch2/external/slc6_amd64_gcc493/data/RecoEgamma/ElectronIdentification/data/PHYS14/EIDmva_EE_5_oldscenario2phys14_BDT.weights.xml
MVABin 3 : MethodName = BDT , type == 2 , Load weights file : /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_3_patch2/external/slc6_amd64_gcc493/data/RecoEgamma/ElectronIdentification/data/PHYS14/EIDmva_EB1_10_oldscenario2phys14_BDT.weights.xml
MVABin 4 : MethodName = BDT , type == 2 , Load weights file : /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_3_patch2/external/slc6_amd64_gcc493/data/RecoEgamma/ElectronIdentification/data/PHYS14/EIDmva_EB2_10_oldscenario2phys14_BDT.weights.xml
MVABin 5 : MethodName = BDT , type == 2 , Load weights file : /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_3_patch2/external/slc6_amd64_gcc493/data/RecoEgamma/ElectronIdentification/data/PHYS14/EIDmva_EE_10_oldscenario2phys14_BDT.weights.xml

It seems we are reading PHYS14 stuff...

**Comment by bianchini** [comment]
Ok, never mind. It was our fault (we are saving phys14 mva ID's for some reason):
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/python/vhbbobj.py#L28
I would comment them out from vhbbobj.py.
I don't see a reason why we should keep them, and it just creates confusion.
Do you have objections? Anybody still using Phys14 ID?

**Comment by degrutto** [comment]
not that I know,
I'd say to comment that line

**Comment by bianchini** [comment]
Done by https://github.com/vhbb/cmssw/pull/413 and https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1701/1/1/1.html
