### ISSUE TITLE
Change V mass for Vtype=2,3

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#429]
At the moment, the V candidate is defined as the sum of the four-momentum of vLeptons_xx[0] and met_xx[0].
I'm suggesting to use the transverse mass, instead of the standard invariant mass, in case of Vtype=2,3 (W decay).
In this way, we could see clearly the W mass peak.

**Comment by perrozzi** [comment]
what about this?

**Comment by arizzi** [comment]
VMt is in the ntuples, it is not V_mass
