### ISSUE TITLE
Check triggers for 80X MC/data

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#436]
we should check that:
- all the needed trigger bits are saved
- we save trigger objects for all relevant triggers (e.g. we were missing those for DoubleBtag triggers)

P.S. does the fact that the MC contains a wrong trigger emulation represent a problem?
Boh..

**Comment by bianchini** [comment]
@scooperstein @GLP90 @swang373 @MDallOsso @pablodecm
Please check that https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/TriggerTableData.py and https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/TriggerObjectsList.py contain all the triggers you need.

**Comment by bianchini** [comment]
@chernyavskaya

**Comment by bianchini** [comment]
Ciao,
any news about this? Please check:

@scooperstein: SingleEle and SingleMu triggers. Beware that Ele23 has been prescaled
@GLP90, @dcurry09: DoubleEle and DoubleMu triggers.
@swang373, @silviodonato: MET triggers
@MDallOsso @pablodecm: HH triggers
@chernyavskaya: VBF triggers
@silviodonato, @d-salerno: ttH all-hadronic triggers
@degrutto, @bianchini: MSSM triggers

For all of them we have to make sure that the trigger bit is listed and the trigger objects are saved.
@silviodonato knows how to implement the latter.

Report here what you find.

**Comment by silviodonato** [comment]
Hi all,
you can find the running HLT paths in [274387](https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/HLTSummary?fromLS=140&toLS=439&RUN=274387&KEY=2002042). As Lorenzo wrote, they have to be compared with [TriggerTableData.py](https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/TriggerTableData.py).

Regarding ZvvHbb I fixed with https://github.com/vhbb/cmssw/pull/446

**Comment by degrutto** [comment]
Hi,

and just to restate,

HLT_Ele23_WPLoose_Gsf_v4 (2044547) 
https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/HLTPath?PATHID=2044547

is prescaled now

**Comment by d-salerno** [comment]
the all hadronic ttH signal trigger names have changed:
"HLT_PFHT450_SixJet40_PFBTagCSV0p72_v_" --> "HLT_PFHT450_SixJet40_BTagCSV_p056_v_"

"HLT_PFHT400_SixJet30_BTagCSV0p55_2PFBTagCSV0p72_v_" --> "HLT_PFHT400_SixJet30_DoubleBTagCSV_p056_v_"

Also, all L1HTT seeds have changed name. For example in the SixJet triggers the L1 seed object goes from:
hltL1sL1HTT175 --> hltL1sHTT280IorHTT300

**Comment by bianchini** [comment]
Thanks! Can you provide a PR?

**Comment by silviodonato** [comment]
Ciao Lorenzo,
I included it in https://github.com/vhbb/cmssw/pull/446/files (and also the VBF, HH4b triggers).

The trigger objects are changed with https://github.com/vhbb/cmssw/pull/447 , but I have to change the code to use the L1 stage-2 trigger objects

**Comment by bianchini** [comment]
Ok, great thanks!

**Comment by dcurry09** [comment]
Hi,

The electron triggers that have to be changed are:

HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v\* ->
HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v3*

HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v\* ->
HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v*

HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_v\* ->
HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_v3*

This is in PR #448
https://github.com/vhbb/cmssw/pull/448

On Thu, Jun 9, 2016 at 10:14 AM, silviodonato notifications@github.com
wrote:

> Hi all,
> you can find the running HLT paths in 274387
> https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/HLTSummary?fromLS=140&toLS=439&RUN=274387&KEY=2002042.
> As Lorenzo wrote, they have to be compared with TriggerTableData.py
> https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/TriggerTableData.py
> .
> 
> Regarding ZvvHbb I fixed with #446
> https://github.com/vhbb/cmssw/pull/446
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/vhbb/cmssw/issues/436#issuecomment-224828485, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEJ5mnSstbYZmGm121YrcBoa5gxV07yQks5qJ8tIgaJpZM4IrQUc
> .

## 

## David Curry

Physics Department
CERN B8 R-031 || University of Florida, NPB 1218
curry@phys.ufl.edu
076 291 0492

**Comment by degrutto** [comment]
Hi David

please do not use v3_, but keep v_!

**Comment by bianchini** [comment]
Done by https://github.com/vhbb/cmssw/pull/447
Closing

**Comment by degrutto** [comment]
Hi all,

contrary t what I said...
TSG decided to have HLT_Ele25_WPTight (no eta restriction) unprescaled!
