### ISSUE TITLE
Are ALL priority1 80X samples there?

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#443]
To follow up https://github.com/vhbb/cmssw/pull/435:
do we have all miniAODv2 samples there? In particular, let's make sure we have the VH signal samples and TT sample to submit the preprouction + regression

**Comment by bianchini** [comment]
@perrozzi 
Ciao Luca, could you check if in the meantime some new sample arrived?

**Comment by perrozzi** [comment]
cfr https://github.com/vhbb/cmssw/pull/471
