### ISSUE TITLE
remove eta restriction on the presence of 2 jets for vtype =0,1,2,3

### ISSUE THREAD

**Issue by azzurrip** [vhbb/cmssw#444]
for extending the use to EW Z/W+jj (VBF Z/W) measurements
will lead to a very small increase in number events in the trees

**Comment by bianchini** [comment]
Can we consider it solved by https://github.com/vhbb/cmssw/pull/506?

**Comment by azzurrip** [comment]
Yes, just tested it and it is fine.
Thanks
