### ISSUE TITLE
Dump good JEC, change GTs

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#450]
We need to dump the correct JEC and link them in vhbb.py

**Comment by bianchini** [comment]
Taken by @degrutto

**Comment by perrozzi** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/smp-j/292.html

**Comment by degrutto** [comment]
see #455 
obtained from here https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC by dumbing  Spring16_25nsV3_MC(DATA)

Checked it makes the pt spectrum slightly softer wrt to (wrongly) applying the 76X correction on 80X as we were still doing

**Comment by bianchini** [comment]
After swtiching to Spring16_25nsV3_DATA, vhbb_combined_data crashes on data:

Traceback (most recent call last):
  File "vhbb_combined_data.py", line 27, in <module>
    looper = Looper( 'Loop', config, nPrint = 1, nEvents = 100)
  File "/mnt/t3nfs01/data01/shome/bianchi/VHbb_80X/CMSSW/python/PhysicsTools/HeppyCore/framework/looper.py", line 85, in **init**
    self.analyzers = map( self._build, config.sequence )
  File "/mnt/t3nfs01/data01/shome/bianchi/VHbb_80X/CMSSW/python/PhysicsTools/HeppyCore/framework/looper.py", line 129, in _build
    obj = theClass( cfg, self.cfg_comp, self.outDir )
  File "/mnt/t3nfs01/data01/shome/bianchi/VHbb_80X/CMSSW/python/PhysicsTools/Heppy/analyzers/objects/JetAnalyzer.py", line 97, in __init__
    self.jetReCalibrator = JetReCalibrator(GT, cfg_ana.recalibrationType, doResidual, cfg_ana.jecPath, **kwargs)
  File "/mnt/t3nfs01/data01/shome/bianchi/VHbb_80X/CMSSW/python/PhysicsTools/Heppy/physicsutils/JetReCalibrator.py", line 41, in **init**
    self.JetCorrector = ROOT.FactorizedJetCorrector(self.vPar)
TypeError: none of the 3 overloaded methods succeeded. Full details:
  FactorizedJetCorrector::FactorizedJetCorrector() =>
    takes at most 0 arguments (1 given)
  FactorizedJetCorrector::FactorizedJetCorrector(const string& fLevels, const string& fTags, const string& fOptions = "") =>
    takes at least 2 arguments (1 given)
  FactorizedJetCorrector::FactorizedJetCorrector(const vector<JetCorrectorParameters>& fParameters) =>
    problem in C++; program state has been reset

**Comment by bianchini** [comment]
So, it is related to the fact that we use CMSSW_8_0_5. 
We should move to 8_0_11 for the fix.

**Comment by jpata** [comment]
according to JetMET 8_0_8_p1 is the minimum version https://hypernews.cern.ch/HyperNews/CMS/get/jes/605.html

**Comment by bianchini** [comment]
Fixed after switchig to 8-0-11
https://github.com/vhbb/cmssw/pull/462

**Comment by perrozzi** [comment]
shall we reopen this?
https://hypernews.cern.ch/HyperNews/CMS/get/jes/609.html

**Comment by jpata** [comment]
Hi, let's make a new PR simply?
