### ISSUE TITLE
Check PU weight

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#451]
Currently, puWeight ~ 0.2 with huge peak at zero: we should replace test/crab/puMC.root with the correct Spring16 distribution or we are screwing up.
Who knows how to get it?

**Comment by bianchini** [comment]
Ok, it shoul be this one:
https://raw.githubusercontent.com/cms-sw/cmssw/CMSSW_8_0_X/SimGeneral/MixingModule/python/mix_2016_25ns_SpringMC_PUScenarioV1_PoissonOOTPU_cfi.py
I can take care

**Comment by perrozzi** [comment]
To complement: all the info concerning pileup, json and lumicalc for 2016 data ara available at
https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2016Analysis

**Comment by bianchini** [comment]
Done with https://github.com/vhbb/cmssw/pull/45

**Comment by bianchini** [comment]
A new pileup json is available:
https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/583.html

**Comment by bianchini** [comment]
added in https://github.com/vhbb/cmssw/pull/462
