### ISSUE TITLE
GenHFHadronMatcher: check the recipe on 80X

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#452]
Is the GenHFHadronMatcher module we run in the preprocessor still fine in 80X?
@jpata: can you please take a look?

**Comment by jpata** [comment]
I've checked that at least the output is filled in the madgraphMLM and powheg-herwig samples. I think by now it is part of CMSSW, so there is no recipe.
For a true physics validation I was going to prepare the tt+X yields per categories...

**Comment by bianchini** [comment]
Ciao joosep, thanks.
Are you saying that we are no longer running standalone code for this? I remember that in the past you had to take local versions of the c++ code.
If it is fine to use the version under CMSSW_RELEASE_BASE, we close this issue.

**Comment by bianchini** [comment]
I'd say we can close
