### ISSUE TITLE
Add PromptReco-v1 to V22

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#479]
Ciao, I see that https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/crab_data/datasets_DATA_25ns_Run2016.txt does not contain PromptReco-v1 samples. 
Is there a reason? If not, could someone add them?

**Comment by bianchini** [comment]
@cvernier

**Comment by cvernier** [comment]
Hi, v1 should contain those runs that did not end up in the golden json, this is why we skip them.
@perrozzi

**Comment by perrozzi** [comment]
Ciao, I don't have yet an official reference but I also think that v1 should not be used, by looking at DAS
v1
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset%3D%2FDoubleEG%2FRun2016B-PromptReco-v1%2FMINIAOD
v2
https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDoubleEG%2FRun2016B-PromptReco-v2%2FMINIAOD&instance=prod%2Fphys03
and at this thread where no intersection between the v1 dataset and the json, one could crosscheck this.
I will try to investigare more

**Comment by bianchini** [comment]
Ok thanks. Any chance that the next json will recover part of it? For the next iteration I would anyway run over it: if we get something, good, otherwise we don't lose much. Unless some of you is 100% sure that they are not to be included.

**Comment by cvernier** [comment]
ok. for v23 we will process them along with the new json.
