### ISSUE TITLE
New BTag CSV 

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#480]
See https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation80X

**Comment by bianchini** [comment]
We should try to switch to the .csv based recipe. Not sure the root files will be still supported. The code is there, but needs to be validated.

**Comment by perrozzi** [comment]
https://github.com/vhbb/cmssw/pull/496

**Comment by perrozzi** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/btag/1324.html
"derived on the 7.7/fb or 9.2/fb data period, these SF are estimated to
be valid for the full ICHEP dataset (12.9/fb)."
https://twiki.cern.ch/twiki/pub/CMS/BtagRecommendation80X/CSVv2_ichep.csv
https://twiki.cern.ch/twiki/pub/CMS/BtagRecommendation80X/cMVAv2_ichep.csv

**Comment by bianchini** [comment]
Done by https://github.com/vhbb/cmssw/pull/506
