### ISSUE TITLE
ttH reHLT TriggerResults missing

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#486]
I'm trying to run on a ttH reHLT sample

input

```
root://xrootd.ba.infn.it//store/mc/RunIISpring16MiniAODv2/ttHTobb_M125_13TeV_powheg_pythia8/MINIAODSIM/PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14-v1/40000/0089CC67-6338-E611-947D-0025904C4E2A.root
```

and I get

```
Disabling as there is no fallback  ('TriggerResults', '', 'HLT') edm::TriggerResults at first failure
Traceback (most recent call last):
  File "vhbb_combined.py", line 154, in <module>
    p.runcall(looper.loop)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/cProfile.py", line 149, in runcall
    return func(*args, **kw)
  File "/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/python/PhysicsTools/HeppyCore/framework/looper.py", line 201, in loop
    self.process( iEv )
  File "/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/python/PhysicsTools/HeppyCore/framework/looper.py", line 259, in process
    ret = analyzer.process( self.event )
  File "/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/python/PhysicsTools/Heppy/analyzers/core/TriggerBitAnalyzer.py", line 73, in process
    triggerResults = self.handles['TriggerResults'].product()
  File "/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/python/PhysicsTools/Heppy/analyzers/core/AutoHandle.py", line 23, in product
    self.ReallyLoad(self.event)
  File "/mnt/t3nfs01/data01/shome/jpata/tth/sw/CMSSW/python/PhysicsTools/Heppy/analyzers/core/AutoHandle.py", line 52, in ReallyLoad
    raise Exception(errstr)
Exception:
            Cannot find collection with:
            type = edm::TriggerResults
            label = ('TriggerResults', '', 'HLT')
```

Any ideas?

**Comment by jpata** [comment]
In the source file I have

```
$ edmDumpEventContent root://xrootd.ba.infn.it//store/mc/RunIISpring16MiniAODv2/ttHTobb_M125_13TeV_powheg_pythia8/MINIAODSIM/PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14-v1/40000/0089CC67-6338-E611-947D-0025904C4E2A.root | grep -i trigger
"TERMCAP", line 20, col 1, terminal 'screen': Illegal character - '^J'
"TERMCAP", line 20, col 1, terminal 'screen': wrong type used for string capability 'kB'
edm::TriggerResults                   "TriggerResults"            ""                "SIM"
edm::TriggerResults                   "TriggerResults"            ""                "RECO"
edm::TriggerResults                   "TriggerResults"            ""                "HLT2"
edm::TriggerResults                   "TriggerResults"            ""                "PAT"
pat::PackedTriggerPrescales           "patTrigger"                ""                "PAT"
pat::PackedTriggerPrescales           "patTrigger"                "l1max"           "PAT"
pat::PackedTriggerPrescales           "patTrigger"                "l1min"           "PAT"
vector<pat::TriggerObjectStandAlone>    "selectedPatTrigger"        ""                "PAT"
```

I guess our code looks for HLT and not HLT2?

**Comment by silviodonato** [comment]
right,
you have to change two lines in the vhbb.py

TrigAna = cfg.Analyzer(
     verbose = False,
     class_object = TriggerBitAnalyzer,
     triggerBits = triggerTable,  #default is MC, use the triggerTableData in -data.py files
_processName = 'HLT2',_

# outprefix = 'HLT'

```
)
```

and

### add trigger objects

from PhysicsTools.Heppy.analyzers.core.TriggerObjectsAnalyzer import TriggerObjectsAnalyzer
from VHbbAnalysis.Heppy.TriggerObjectsList import *
TriggerObjectsAna = TriggerObjectsAnalyzer.defaultConfig
TriggerObjectsAna.triggerObjectsCfgs = triggerObjectCollections
_TriggerObjectsAna.triggerBitsInputTag = ('TriggerResults','','HLT2')_

Still, there is the problem that we need two different processName for 
background and signal (reHLT).

Cheers,
Silvio.

**Comment by jpata** [comment]
yes, that's the problem that came to my mind now that we will be running it over grid... I don't have a smart fix right now. Maybe providing a dict which looks up the sample name at runtime?

**Comment by silviodonato** [comment]
I think so.  We can simply put at the end of vhbb.py :

if "reHLT" in sample.files[0]:
    TriggerObjectsAna.triggerBitsInputTag = ('TriggerResults','','HLT2')*
    TrigAna.processName =  ('TriggerResults','','HLT2')

to solve the problem

**Comment by silviodonato** [comment]
Uh, now I see the problem... 
This change would not fix the problem on CRAB, because it overwrites the samples.
We should modify 
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/crab/heppy_crab_script.py#L33

@arizzi  do you have any better idea?

**Comment by arizzi** [comment]
can we use the fallback mechanism of the AutoHandle?

**Comment by jpata** [comment]
I don't know about that mechanism, but a cursory look says that would also work.

**Comment by jpata** [comment]
so @arizzi @bianchini @perrozzi & other vhbb maintainters, which approach do you prefer? the one I have in the PR (can we merge) or some other one?

**Comment by perrozzi** [comment]
For V23 @cvernier and I split. I did the non-reHLT and she did the data and the reHLT. 
Caterina did you use two branches or use a trick?

**Comment by jpata** [comment]
@perrozzi, we still need this code. Not sure why this was closed.
@cvernier I'm a bit lost here: https://github.com/vhbb/cmssw/pull/522

**Comment by gkasieczka** [comment]
Yes, we should reopen this.

**Comment by perrozzi** [comment]
unless I am missing something, shouldn't have https://github.com/vhbb/cmssw/pull/522 and https://github.com/vhbb/cmssw/pull/487 fixed it?

**Comment by perrozzi** [comment]
@cvernier please (re-)confirm

**Comment by arizzi** [comment]
I guys, not sure about the conclusion of this thread but as I pointed to some of you in july there is a feature of AutoLabel that would allow to specify a second label in case the first getbylabel fails. Can we try using that (i.e. exposing the fall back  label to our config) ?

**Comment by perrozzi** [comment]
let's reopen, no problem from my side

**Comment by gkasieczka** [comment]
Ok, I will look into a solution using AutoLabel

**Comment by gkasieczka** [comment]
#528 should fix the issue. Tested on a "normal" and a reHLT file.
