### ISSUE TITLE
New pileup json soon available

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#505]
See https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2685.html

**Comment by jpata** [comment]
what's the script you've used to update the PU?

**Comment by perrozzi** [comment]
@capalmer85 might provide more info as he is working on it.

what I learned is the following:
1) for a given campaign, heppy picks the data pu from here
https://github.com/perrozzi/cmssw/blob/V23/VHbbAnalysis/Heppy/test/puData.root
and the pu mc from here
https://github.com/perrozzi/cmssw/blob/V23/VHbbAnalysis/Heppy/test/puMC.root
2) each campaign is usually backed-up here
https://github.com/perrozzi/cmssw/tree/V23/VHbbAnalysis/Heppy/test/Lumi
3) the mcpu is always the same while makeDataPUfile.sh (inside each subfloder) can be used to produce the outputData.root for given input JSON, pileup_latest.txt and minimum bias cross section
4) the pileup_latest.txt comes from here
https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions16/13TeV/PileUp/
and can be used for any json, in principle

I tried to do some tests in the last days and @scooperstein tested them by applying the data/mc ratio as weight, but the agreement for datasets including the last chunk of data doesn't look good.
The data PU profile involves the use of number of reconstructed vertices, which is heavily affected by HIP which is not reproduced in MC, resulting in a biased/suboptimal estimate of the effective minbias cross section used in the script.

Following a very recent email from chris, the cross section should be 69.2 ± 4.6%
https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/613/2/1/1/1.html

**Comment by capalmer85** [comment]
Hi Everyone,

I think that Luca has summarized well. HIP and beam spot differences in MC & data have made life hard for vertex efficiency.  The HIP effect is a function of total instantaneous luminosity so at the beginning of a recent fill it looks like the total inefficiency could be higher than 10% wrt to current MC vertex reconstruction.

So we changed the recipe to match data and MC in rho and also made some attempts to correct the vtx reconstruction efficiency.  (The latter was not a complete success but seemed to go in the right direction.)

Punchline:  look at rho after the re-weighting now.

**Comment by jpata** [comment]
@perrozzi could you document (or maybe just do yourself in case it's easier :) ) the PU update procedure? I'd like to submit new ntuples with updated PU weights tomorrow to make meaningful data/MC comparisons on Monday.

**Comment by perrozzi** [comment]
doing reverse engineering of what I wrote above, you need to:

1) create a V24 folder here
https://github.com/vhbb/cmssw/tree/vhbbHeppy80X/VHbbAnalysis/Heppy/test/Lumi
copying the V23 files in it, to start with

2) substitute the JSON with the one you need (likely the ICHEP JSON /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Cert_271036-276811_13TeV_PromptReco_Collisions16_JSON.txt from https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2689.html)

3) redownload the pileup_latest.txt from here
https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions16/13TeV/PileUp/pileup_latest.txt

3) the mcpu is always the same (although you can recreate it with makeMChisto.py)

4) the outputData.root (plus up/down variations) for the given input JSON, pileup_latest.txt and minimum bias cross section can be obtained by running makeDataPUfile.sh after editing it.
@capalmer85 might want to specify the latest and greatest effective minimum bias cross section, to my knowledge it is 69.2 ± 4.6%

5) copy the produced root files back to 
https://github.com/vhbb/cmssw/tree/vhbbHeppy80X/VHbbAnalysis/Heppy/test/
as the code will pick them up from there

6) as far as I understood, the distribution you will need to compare is not the number of reconstructed primary vertices which suffers from the HIP effect in data, which is not reproduced in MC (i.e. the agreement there will be bad) but the "rho" variable, which is supposed to be much less sensitive to HIP and is the real target of the reweighting. I am not 100% sure how is defined and if is included in the ntuples, I assume so, @bianchini might confirm

**Comment by jpata** [comment]
thank you, I will update the PU then.

**Comment by jpata** [comment]
Maybe we need to increase the max PU bin, how about 75:

```
Consider using a higher value of --maxPileupBin
Mean 50.619800, RMS 12.121072, Integrated probability 0.479586
```

Also, is this normal?

```
Run 274969, LumiSection 393 not found in Lumi/Pileup input file. Check your files!
```

**Comment by perrozzi** [comment]
yes, in the sense that so far ther are no really events above 50 (but you could think of enlarging, most likely some hardcoded 50 might need to be changed in the code)
and for run 274969 read https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2686/1/1.html
