### ISSUE TITLE
leptonic trigger efficiencies from reHLT

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#508]
discussed with @bianchini about measuring ad-hoc leptonic trigger efficiencies for the no-reHLT background samples from the signal sample.

@scooperstein @glp90 have you maybe already worked on it?

**Comment by jpata** [comment]
What I would do is:

1) take the vhbb sample, tt+H(bb) reHLT events
2) for events with exactly one good signal lepton (passing ID), derive a pt-eta dependent turn-on for the SL triggers (2D map), independently for mu/e
3) for events passing the DL selection (exclusive to SL), derive 2x 2D maps (pt_high, eta_high) and (pt_low, eta_low) for the turn-on of the DL paths, independently for mumu, emu, ee
4) make a module in vhbb that calculates these "trigger weights" given the 1-2 lepton pt, eta, flavours

For this to be generally applicable, what baseline ID should I use? The one of ttH(bb) is slightly tighter than the one in the vhbb `selLeptons` afaik.

**Comment by jpata** [comment]
@silviodonato have you maybe thought about this already? trying to avoid duplication...

**Comment by GLP90** [comment]
The way it is currently done (@scooperstein: correct me if I am wrong) is to use MC without any trigger applied and to multiply by the data trigger efficiency, provided centraly by the POGs. What would be the gain to calculate "our own" trigger weight ?

**Comment by bianchini** [comment]
Gael: as we discussed before, we should:
- use the reHLT signals amples to derive the MC trigger efficiency in fine pT/eta binning, so we can simulate as good as we want the trun-on.
- apply this efficiency on the simulated samples as event weights
- apply data/MC SF as an event weight: the SF are typically more uniform vs pT/eta than the efficiency themselves.

**Comment by jpata** [comment]
I've cleaned up the ttH(bb) trigger paths in https://github.com/vhbb/cmssw/pull/512

**Comment by jpata** [comment]
@bianchini @perrozzi @GLP90 @silviodonato

I re-derived the Mu27 (as a placeholder for Mu22) MC trigger efficiency curves with the binning from the talk referenced by Gael [1]. I didn't change anything about the lepton ID or Iso, now I still use the inline definitions of selLeptons, this is also partial statistics only.

[trig_2d.pdf](https://github.com/vhbb/cmssw/files/388172/trig_2d.pdf)
[trig_mu_proj_eta.pdf](https://github.com/vhbb/cmssw/files/388173/trig_mu_proj_eta.pdf)
[trig_mu_proj_pt.pdf](https://github.com/vhbb/cmssw/files/388174/trig_mu_proj_pt.pdf)

Let me know if you think it's suitable. I will need to press the button soon today on re-submitting the vhbb on ttH(bb) in order to get the Mu22 trigger bits [2].

Now the question is: 
1) which exact Iso & ID we want? 
2) What are all the trigger bits we care about? I would use the ones relevant for ttH [3], but maybe you have special requests.

[1] https://indico.cern.ch/event/556633/contributions/2242544/attachments/1308702/1957171/2016.07.13_MuonPOG_SingleMuTrigEff_80X_KPLee_v1.pdf
[2] https://github.com/vhbb/cmssw/pull/512
[3] https://github.com/vhbb/cmssw/pull/514/files#diff-5ab08f49b4314b3b14e5d486c3e9177aR31

**Comment by perrozzi** [comment]
ciao
- in which sense Mu27 as a placeholder for Mu22? is the latter available?
- how did you compute the uncertainties? they seem to be very large (you might consider using the TEfficiency class in case https://iktp.tu-dresden.de/IKTP/Seminare/IS2010/Christian_Gumpert.pdf)
- there seem to be still a bit of stat fluctuation. which fraction of the dataset did you use?
- in case we don't have enough statistics to remove the stat fluct, we can consider parametrizing the curve, it has been done in the past and I can find a reference

1) As Gael was mentnioning, for Zll one should compute them on top of the Loose ID, Loose Iso (< 0.25) while for Wlv it should be on top of the Tight ID, Tight Iso (<0.15)
The Tight ID, Tight Iso T&P will be provided by the MUON POG but still is worth providing a finer binning for MC.
For Loose ID, Loose Iso T&P results on data need to be produced, @GLP90 might want to jump on it
2) @silviodonato or @degrutto might comment more, I think the HLT unprescaled path we (VH) care the most is (Mu22 OR tkMu22)

ciao
luca

**Comment by jpata** [comment]
Thanks!

Quick answers
- it's s tiny fraction of ttH by design to get feedback
- Mu27 for code validation, we didn't save Mu22 in vhbb, I need to rerun the signal dataset in order to have it

Long answer in a bit

**Comment by GLP90** [comment]
I is currently not possible to produce the trigger efficiency SF using the tnp tool, the Ntuples don’t have the proper trigger emulation at the moment. One should compute them with the cut and count on the signal dataset, following the same binning as in [1].

[1] https://indico.cern.ch/event/556633/contributions/2242544/attachments/1308702/1957171/2016.07.13_MuonPOG_SingleMuTrigEff_80X_KPLee_v1.pdf https://indico.cern.ch/event/556633/contributions/2242544/attachments/1308702/1957171/2016.07.13_MuonPOG_SingleMuTrigEff_80X_KPLee_v1.pdf

**Comment by jpata** [comment]
sorry for my naivete, this question just occurred to me: don't we have a tautological definition of the data/mc scale factors in case we derive them from the emulation, not the real trigger?

**Comment by jpata** [comment]
@GLP90 explained to me.

we do `MC * trigger_emu * (eff_data/eff_mc)`, where
- `trigger_emu` should be with a fine binning, capturing the turn-on, what I'm doing now
- `eff_mc` is with the broad POG binning, we also have to derive because the POG cannot do
- `eff_data` we get from the POG

we can use the same code for both.

**Comment by perrozzi** [comment]
Ciao, TnP would ensure in (close-to) one go the same binning for data and mc,
so that when producing the data efficiencies one could produce also the MC efficiencies and automatically derive the SF.
When deriving the cut&count efficiencies in MC one would like to make fine bins to properly model the turn-on but then should make another set of efficiencies with coarser binning matching the data.
Not big deal, we can derive the 2 sets with cut&count.

**Comment by jpata** [comment]
I've rerun VHBB including #512 (i.e. the Mu22 triggers). I derived again these turn-ons, this time with the coarse binning as before, and as well a finer binning in pt=(15,30] with an 0.5 step. I've introduced the tight and loose ID criteria for the leptons. I also fitted an `erf` to the turn-ons "by hand" in bins of eta. I've processed roughly 80%  of ttH statistics, I have ~330k events with a tight muon that also pass the ID. 

Here are the fitted turn-ons (along with fit 1000 toys around fit uncertainties, assuming fully uncorrelated parameters):

[trig_mu_proj_pt_fine.pdf](https://github.com/vhbb/cmssw/files/390695/trig_mu_proj_pt_fine.pdf)
**EDIT**: fixed title

To get any accurate shape on the actual turn on is very hard: it's a sharp feature that requires extremely good MC statistics. Additionally, one would have to make the final trigger emulation a piecewise function of the histogram lookup or fit, depending on which region you are in. I guess this code can get messy and error prone. Moreover, the fit may require fine-tuning.

What do you think? Should we go with this fitting, or just a 2D ratio lookup in the fine-binned histograms? One could do at runtime a dicing around the ratio with it's uncertainties, but it may be an overkill.

For completeness, here are the coarse-binned histograms.
[trig_mu_proj_eta.pdf](https://github.com/vhbb/cmssw/files/390549/trig_mu_proj_eta.pdf)
[trig_mu_proj_pt.pdf](https://github.com/vhbb/cmssw/files/390550/trig_mu_proj_pt.pdf)

For the moment I didn't use TEfficiency, because these 1D projections of the 2D pt,eta space are just illustrations.

**Comment by jpata** [comment]
@bianchini @degrutto what would you recommend as a cross-check of this trigger emulation? Would it be sufficient to just re-exctract the turn ons from the weight?

**Comment by degrutto** [comment]
yes,
and probably just check that for example they are flat vs  Njets/Nbjets or additional leptons

**Comment by perrozzi** [comment]
can this be closed?

**Comment by jpata** [comment]
@perrozzi closing, as the PR has been merged.
