### ISSUE TITLE
Update b-tag SF (with HIP mitigation)

### ISSUE THREAD

**Issue by gkasieczka** [vhbb/cmssw#521]
Quoth Wuming Luo
"The b-tagging SFs have been updated for a while. I think I might have forgotten to send them around.
I’m very sorry about the delay. You can find them here on lxplus:
/afs/cern.ch/user/l/lwming/public/csvSFs2016/ICHEP_12p9_8_5_set/_8_5_"

Can somebody uodate these?

**Comment by scooperstein** [comment]
Hi,
Thanks for sharing these. I think it would be very useful to try using these updated SF's on V23 via an external macro in the time before we have V24 ready. Are these intended to be used on top of the 8_0_X samples (like V23)? Or do we need to use these on samples which incorporate the HIP mitigation at the tracking level?

**Comment by scooperstein** [comment]
@degrutto @bianchini @perrozzi @capalmer85

**Comment by degrutto** [comment]
Hi

as far as I understand, these SFs are to be used for the full iCHEP dataset 13 fb-1 and or a dataset with >= the first 7.7fb-1 of 2016 data

**Comment by perrozzi** [comment]
as far as I remember, this PR https://github.com/vhbb/cmssw/pull/496 should contain the SF computed on 7.7/fb and applicable to the ICHEP dataset (~13/fb)
@bianchini should confirm

**Comment by scooperstein** [comment]
Okay thanks for the info. Do you know if they can be used on the 80X samples we have processed? My understanding is that the HIP mitigation also includes corrections at the tracking level that we won't have available until the ReReco.

**Comment by perrozzi** [comment]
I briefly discussed with @arizzi. 
bottom line is:
- the snippet to produce a new csv with mitigation included exists (andrea wrote it) and can be run on miniaod in principle
- dinko should have included it in the jet tools code (need to xcheck)
- is probably better to proceed with an intermediate campaign now and postpone this new development, also in view of the forthcoming decision on the rereco

**Comment by gkasieczka** [comment]
@perrozzi 
Just to make sure there is no misunderstanding. You propose to wait with deploying our own version of the BTV track selection until the timescale of rereco is certain. That would be fine for me.

But we should still update the SFs to the ones covering the full ICHEP dataset, no?

**Comment by perrozzi** [comment]
ciao @gkasieczka, as I wrote above (and as far as I remember) the PR #496 should contain the SF computed on 7.7/fb and applicable to the ICHEP dataset (~13/fb).
Am I wrong?
(@bianchini and/or @cvernier should confirm)

**Comment by bianchini** [comment]
Ciao, I don'te remember but I think so: https://github.com/vhbb/cmssw/commit/457a26c58b954923ea7961e7c91ff8f79c663146
In generak:
if the code points to CSVv2_ichep.csv: OK
if the code points to CSVv2_4invfb.csv: BAD

**Comment by perrozzi** [comment]
ok, so it looks like the PR ports the sf to the ichep dataset.

**Comment by gkasieczka** [comment]
Ok, excellent. Thanks for checking - so we can close this issue.

**Comment by perrozzi** [comment]
linked to https://github.com/vhbb/cmssw/pull/530
here the corresponding SF for the ICHEP dataset
/afs/cern.ch/user/l/lwming/public/csvSFs2016/ICHEP_12p9_8_5_set/
we will need to check how they compare to the current dataset (~25/fb) and eventually ask Wuming to compute them on the new dataset. any comment?

**Comment by degrutto** [comment]
hi,

should we now switch to the SF with hip (BTV) mitigation from Robin? I will send him an email to be sure we pick the correct ones

**Comment by degrutto** [comment]
Hi all,

so according to Robin the most recent files to use (for SF for HIP mitigations) are (derived on run2016B and C)

/afs/cern.ch/user/l/lwming/public/csvSFs2016/ttH_BTV_cMVAv2_13TeV_2016BC_7p6_2016_08_13.csv
/afs/cern.ch/user/l/lwming/public/csvSFs2016/ttH_BTV_CSVv2_13TeV_2016BC_7p6_2016_08_13.csv

**Comment by degrutto** [comment]
please see #542

@bianchini @arizzi

**Comment by degrutto** [comment]
as #542 has been merged, we can close this! thanks
