### ISSUE TITLE
MET filters for Znn 

### ISSUE THREAD

**Issue by cvernier** [vhbb/cmssw#525]
Missing in the ntuples:
- badMuon (new.gif not available in miniAOD v2, see [1])
- badCharged hadron (new.gif not available in miniAOD v2, see [1])
- Flag_CSCTightHalo2015Filter had been replace by the Flag_globalTightHalo2016Filter for the ICHEP analysis
- Flag_globalTightHalo2016Filter is available only in 80X miniAODv2

[1] https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#MET_Filter_Recommendations_for_R

@degrutto @swang373

**Comment by degrutto** [comment]
Hi, 

ok, see 

#526

when we will have the V24 (and on) please use as MET filters

(Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_goodVertices && Flag_eeBadScFilter && Flag_GlobalTightHalo2016Filter)

while for V23 just (for now)

(Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_goodVertices && Flag_eeBadScFilter)

and just for completeness in 2015 one has to use 

(Flag_hbheIsoFilter && Flag_hbheFilterNew && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_goodVertices && Flag_eeBadScFilter && Flag_CSCTightHalo2015Filter)"

**Comment by degrutto** [comment]
Hi,

just to comment further if I take the 9 fb-1 of MET dataset in V23 and I do

tree->Draw("Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_goodVertices && Flag_eeBadScFilter", "json && Vtype==4 && met_pt>150 && HCSV_pt>130 && Sum$(Jet_pt[hJCidx]>30)>=2")

I got 85% the efficiency of the MET filters, which sounds reasonable, 
I don;t have now some V23 signal sample to look at, maybe   @swang373 
 can make a quick check?
