### ISSUE TITLE
check PUid wp

### ISSUE THREAD

**Issue by cvernier** [vhbb/cmssw#534]
here the 80x 
https://www.dropbox.com/s/x3wvesbyavtiqg3/PUIDpres1.pdf?dl=0
From:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD

**Comment by silviodonato** [comment]
The current jet PU ID code was modified in June, the original PR is here [1](https://github.com/CERN-PH-CMG/cmg-cmssw/pull/649) and it was based to 76X. 
Looking at [2](https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetID#Information_for_13_TeV_data_anal), preliminary 80X WPs  are available and they can be obtained directly from 80X MiniAODv2.

Example from [2](https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetID#Information_for_13_TeV_data_anal):
print "Passes loose: ", bool(jet.userInt("pileupJetId:fullId") & (1 << 2)) ...

**Comment by arizzi** [comment]
We should check JetID and PUJetID for rereco/newMC

**Comment by gkasieczka** [comment]
Using the ReReco will give us up-to-date version of PU Jet ID:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/PileupJetID#Information_for_13_TeV_data_anal

There was a recent change to Jet ID criteria for 2.7 < abs(eta) < 3 jets:
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016

**Comment by arizzi** [comment]
see #558 , the fact that miniAOD contains the new PU ID doesn't mean we are using it
