### ISSUE TITLE
Improve leptonSF

### ISSUE THREAD

**Issue by bianchini** [vhbb/cmssw#548]
https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/VHbbAnalysis/Heppy/python/leptonSF.py#L50-L66 
could be imrpoved.

**Comment by bianchini** [comment]
@GLP90: Gael, could you take a look: there are operations on strings that could be moved to the init function to speed up the code.

**Comment by GLP90** [comment]
@bianchini In order to assign the SF within the correct pT-eta bin, it is necessary to loop over the json entries for each new event. So I don't see how the e.g. etaL and etaH can be defined in the initialisation since they are different for each lepton. Am I missing something ?

**Comment by jpata** [comment]
@GLP90 maybe you could do the parsing of the strings once in a setup function (like `__init__`) and prepare some sort of a lookup or map that will be used in the `get_2D` function that is faster?

**Comment by arizzi** [comment]
you should just do the string to float conversion in init and prepare a dict (or any other structure.. perhaps even a ROOT.TH2F that has FindBin implemented in c++ !! ) to go faster event by event.

**Comment by GLP90** [comment]
Ok got it, thanks for the suggestion. I will make the modifications.

**Comment by bianchini** [comment]
Done here: https://github.com/vhbb/cmssw/pull/556
