### ISSUE TITLE
CMSSW Version

### ISSUE THREAD

**Issue by gkasieczka** [vhbb/cmssw#549]
I'm getting ugly merges (ie many checked out packages) when merging 
`git cms-merge-topic vhbb:vhbbHeppy80X`
into a clean CMSSW 8_0_19 as well as a clean 8_0_19_patch1.

Is there another version to use, did we break sparse checkouts (or did I screw something up?)

Thank you!
Cheers,
Gregor

**Comment by perrozzi** [comment]
try with 
git cms-merge-topic -u vhbb:vhbbHeppy80X

ciao
luca

**Comment by gkasieczka** [comment]
Nice, did not know about this option.

Thanks!
