### ISSUE TITLE
Problem with reproducing HCSV_reg_mass from heppy variables

### ISSUE THREAD

**Issue by BenjaminMesic** [vhbb/cmssw#554]
I tried to reproduce H_*_mass from heppy jet variables ( pt, eta, phi, mass). I can reproduce the mass for HCSV_mass and H_mass, but I get different result for HCSV_reg_mass and H_reg_mass.

Dataset: SingleElectron, SingleMuon (V23)

Here is just the output for one event ("similiar effect" with other events as well... )

Event number:  536290689
- HCSV_mass: 81.8136367798 
  M_hJCidx: 81.8136387957
- H_mass:  291.109100342
  M_hJidx: 291.109089935
- HCSV_reg_mass: **92.6383361816**
  M_reg_hJCidx: **88.5801281587**
- H_reg_mass: **297.02142334**
  M_reg_hJidx: **296.090265771**

As you can see difference between HCSV_reg_mass and M_reg_hJCidx ~ 4.0

M_\* are values which I calculated by hand:
e.g.  

```
M_reg_hJCidx =
ROOT.VHbb.M(
 _tree.Jet_pt_reg[_tree.hJCidx[0]],
 _tree.Jet_eta[_tree.hJCidx[0]],
 _tree.Jet_phi[_tree.hJCidx[0]],
 _tree.Jet_mass[_tree.hJCidx[0]],
 _tree.Jet_pt_reg[_tree.hJCidx[1]],
 _tree.Jet_eta[_tree.hJCidx[1]],
 _tree.Jet_phi[_tree.hJCidx[1]],
 _tree.Jet_mass[_tree.hJCidx[1]]
)
```

where M is function which calculates invariant mass.

**Comment by arizzi** [comment]
I guess you should scale the whole p4 of the Jet with the regression factor, i.e. including the mass

M_reg_hJCidx =
ROOT.VHbb.M(
 _tree.Jet_pt_reg[_tree.hJCidx[0]],
 _tree.Jet_eta[_tree.hJCidx[0]],
 _tree.Jet_phi[_tree.hJCidx[0]],
 _tree.Jet_mass[_tree.hJCidx[0]]\* _tree.Jet_pt_reg[_tree.hJCidx[0]]/ _tree.Jet_pt[_tree.hJCidx[0]],
 _tree.Jet_pt_reg[_tree.hJCidx[1]],
 _tree.Jet_eta[_tree.hJCidx[1]],
 _tree.Jet_phi[_tree.hJCidx[1]],
 _tree.Jet_mass[_tree.hJCidx[1]]\* _tree.Jet_pt_reg[_tree.hJCidx[1]]/ _tree.Jet_pt[_tree.hJCidx[1]],
)

**Comment by BenjaminMesic** [comment]
Thank you. It works.

Issue solved :)
