### ISSUE TITLE
V25 checklist

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#557]
TTH would like to do another submission very soon, in the next days.

Currently we have in the pipeline:

GSF ele SF: https://github.com/vhbb/cmssw/pull/556

@bianchini do you see any more upcoming things we should wait for?

**Comment by bianchini** [comment]
Ciao Joosep, if we don't care care about looking beyond RunD, we can move on.

**Comment by jpata** [comment]
I've submitted a run of VHBB+ttH with #556 under the tag `Sep29_v1`:

[dashboard](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Joosep+Pata&refresh=60&table=Mains&p=1&records=-1&activemenu=1&pattern=*Sep29_v1*&task=&from=&till=&timerange=lastMonth)
