### ISSUE TITLE
Update list of trigger bits

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#56]
we should update the list of trigger bits once we switch to 74X based on the menu that will go in 74X reco campaign.
@silviodonato

**Comment by silviodonato** [comment]
I've update the google DOC: https://docs.google.com/spreadsheets/d/1m7rAF1BBnTuxdElk3x0s_DuC4zOOTWgYDgbRnLnUt_I/edit#gid=252529807.
I will send the trigger list soon.

**Comment by silviodonato** [comment]
https://github.com/vhbb/cmssw/pull/57

**Comment by arizzi** [comment]
closed with #62
