### ISSUE TITLE
GenJet_pdgId is always zero in DY sample??

### ISSUE THREAD

**Issue by tseva** [vhbb/cmssw#562]
Dear all, 
I'm suing this trees to do Zbb ( and maybe also Z->bb) analysis, I have a problem with following variables:
1. I assumed this variable: GenJet_pdgId represents type of gen jet (ucdsb)? But it seems it's value is always zero ?
1a. When using this variable: GenJet_numBHadrons ,  we seem to get ~200 gen b jets
2.  is there some other way to get gen jet flavour out from the trees ?
3. Is there somewhere a definition of variable meanings ( what they represent) ?

Thanks for any kind of input, 
Tomislav

**Comment by bianchini** [comment]
Hi Tomislav,
you should use Jet_mcFlavour for the parton flavour of the gen-jet associated with some reco-jet (21, 0, 1,2,...). We use Jet_hadronFlavour==5,4,0 to define b-jets, c-jets, and all the rest. Use GenJet_numB(C)Hadrons[Jet_mcIdx[x]] to count the number of such hadrons for reco-jet of index 'x'
This definition comes form ghost matching of hadrons, while mcFlavour from geometrical matching of partons (on the last I am not 100% sure though).  

The code is quite involved in this respect. Some definitions come from miniAOD, other from Heppy. From my experience, the best thing is to check out the whole package and search the infos with 'grep' under either VHbbAnalysis/Heppy or PhysicsTools/Heppy

**Comment by arizzi** [comment]
can we close this?

**Comment by tseva** [comment]
Sorry forgot to do it. So please close it.

Tomislav
