### ISSUE TITLE
new GT

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#573]
Spring16_25nsV10, https://hypernews.cern.ch/HyperNews/CMS/get/jes/639.html

**Comment by degrutto** [comment]
Hi, 

how do we make sure when we run on data we use the correct GT? Is there some code already from some repository we can steal or for example we work at crab submission level?

**Comment by jpata** [comment]
Ciao, sorry I'm not precisely sure what your question is, but the GT is configured in the usual way in `vhbb.py`. Also someone needs to dump the JEC files into the `data` dir.

**Comment by degrutto** [comment]
Hi @jpata 
I am referring to the fact that I read 
IOV BCD: [1,276811] corresponds to Spring16_25nsV10BCD_DATA.tar.gz
IOV E: [276831,277420] corresponds to Spring16_25nsV10E_DATA.tar.gz
IOV F: [277772,278801] corresponds to Spring16_25nsV10F_DATA.tar.gz
IOV G: [278802,Infinity] corresponds to Spring16_25nsV10p2_DATA.tar.gz

I'm not sure, actually I don't think that in heppy we have an IOV (i.e. a way to associate the run number to the payload) as we have in the full framework

**Comment by jpata** [comment]
ah, I see. Good question indeed... For crab submission we can pass the GT as an extra argument, I think.

**Comment by jpata** [comment]
to confirm, likely we'll need run-dependent GT/JEC configuration for data.

**Comment by arizzi** [comment]
I'll take care of this in the crab script, can someone meanwhile dump all payloads in the relevant vhbb heppy directories and make a PR?

**Comment by jpata** [comment]
OK, doing it!

**Comment by jpata** [comment]
https://github.com/vhbb/cmssw/pull/593

**Comment by jpata** [comment]
looks like the newest GT for Data is `Spring16_23Sep2016V2`, the one for MC is identical to 25nsV10: https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC

Waiting for #592 to be merged in order to test coherently in CMSSW 8_0_21.

**Comment by arizzi** [comment]
but we were using Spring16_25nsV6_MC... so we still need to update, right?

**Comment by jpata** [comment]
yes, we skipped one.

**Comment by arizzi** [comment]
crab mechanism implemented too #599  (to be tested after some issue with running on data are solved).
We can close this issue
