### ISSUE TITLE
CMVA SF = 0 for pt > 300 GeV

### ISSUE THREAD

**Issue by cvernier** [vhbb/cmssw#575]
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/btagSF.py#L103
This has to be updated from 320 to 300 otherwise SF are always 0 if pt > 300 GeV.

**Comment by bianchini** [comment]
Ciao, I fixed it in https://github.com/vhbb/cmssw/pull/568/commits/afe74cd32896ec259f351a5a910ae058948c30bc
We will get it once we merge my PR on the kin fit.

**Comment by cvernier** [comment]
thanks!
