### ISSUE TITLE
add softlepton id  for electrons and check what is ther efor muons

### ISSUE THREAD

**Issue by degrutto** [vhbb/cmssw#58]
for v12

**Comment by arizzi** [comment]
do you have some code for this?

**Comment by degrutto** [comment]
Hi Andrea,

sorry I forgot to update you on the status
looseIdSusy is fine for now, until new loose id will be provided (for electrons as well).
I suspect they will update the looseIdSusy anyway....

I'll close the milestone, as actually not needed

   Michele

**Comment by arizzi** [comment]
wasn't some flag missing in the lepton_in_jet ?

**Comment by degrutto** [comment]
Hi,

so I'd say we want to use "soft" leptons for two cases:

A) for the b-jet regression, we want to have electrons in jet down to 5ish GeV or so, witha  minimum id, and I believe wjat is done now is fine
https://github.com/vhbb/cmssw/blob/vhbbHeppy741patch1/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L172

where the inclusive leptons is defined in 
https://github.com/vhbb/cmssw/blob/vhbbHeppy741patch1/PhysicsTools/Heppy/python/analyzers/objects/LeptonAnalyzer.py

  inclusiveMuons = []
        inclusiveElectrons = []
        for mu in allmuons:
            if (mu.track().isNonnull() and mu.muonID(self.cfg_ana.inclusive_muon_id) and 
                    mu.pt()>self.cfg_ana.inclusive_muon_pt and abs(mu.eta())<self.cfg_ana.inclusive_muon_eta and 
                    abs(mu.dxy())<self.cfg_ana.inclusive_muon_dxy and abs(mu.dz())<self.cfg_ana.inclusive_muon_dz):
                inclusiveMuons.append(mu)
        for ele in allelectrons:
            if ( ele.electronID(self.cfg_ana.inclusive_electron_id) and
                    ele.pt()>self.cfg_ana.inclusive_electron_pt and abs(ele.eta())<self.cfg_ana.inclusive_electron_eta and 
                    abs(ele.dxy())<self.cfg_ana.inclusive_electron_dxy and abs(ele.dz())<self.cfg_ana.inclusive_electron_dz and 
                    ele.lostInner()<=self.cfg_ana.inclusive_electron_lostHits ):
                inclusiveElectrons.append(ele)
        event.inclusiveLeptons = inclusiveMuons + inclusiveElectrons
# inclusive very loose muon selection
    inclusive_muon_id  = "POG_ID_Loose",
    inclusive_muon_pt  = 3,
    inclusive_muon_eta = 2.4,
    inclusive_muon_dxy = 0.5,
    inclusive_muon_dz  = 1.0,

and  inclusive_electron_id  = "",
    inclusive_electron_pt  = 5,
    inclusive_electron_eta = 2.5,
    inclusive_electron_dxy = 0.5,
    inclusive_electron_dz  = 1.0,
    inclusive_electron_lostHits = 1.0,


 B) for vetoying additional isolated leptons from ttbar or W/jets for example, in WlnHbb and especially ZnnHbb. For this we need a minimum id "with isolation" 
and I'd say the loose id here which I understand is transfterred in the looseIdSysy should be ok
 # loose muon selection
    loose_muon_id     = "POG_ID_Loose",
    loose_muon_pt     = 5,
    loose_muon_eta    = 2.4,
    loose_muon_dxy    = 0.05,
    loose_muon_dz     = 0.2,
    loose_muon_relIso = 0.4,
# loose electron selection
    loose_electron_id     = "", #POG_MVA_ID_NonTrig_full5x5",
    loose_electron_pt     = 7,
    loose_electron_eta    = 2.4,
    loose_electron_dxy    = 0.05,
    loose_electron_dz     = 0.2,
    loose_electron_relIso = 0.4,
    loose_electron_lostHits = 1.0,


Are you asking to add some extra id requirement  in A) ?
