### ISSUE TITLE
update training for regression

### ISSUE THREAD

**Issue by cvernier** [vhbb/cmssw#589]
A Summer16 ttbar sample is needed to produce the new training.

**Comment by arizzi** [comment]
how many events?

**Comment by cvernier** [comment]
500k events of ttbar

**Comment by arizzi** [comment]
submitting right now (I assume it doesn't depend on other still to merge stuff, right??)

**Comment by cvernier** [comment]
just the updated JEC

**Comment by arizzi** [comment]
have a look
/store/user/arizzi/VHBBHeppyA25/TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/VHBB_HEPPY_A25_TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-Py8__RunIISummer16MAv2-PUMoriond17_80r2as_2016_TrancheIV_v6-v1/170109_164717/0000/

more files coming after resubmit di maxram

**Comment by arizzi** [comment]
#623
