### ISSUE TITLE
Protect  LHE weights producer

### ISSUE THREAD

**Issue by arizzi** [vhbb/cmssw#628]
example failing sample:

== CMSSW: 14-Jan-2017 06:00:52 EST  Successfully opened file root://cms-xrd-global.cern.ch//store/mc/RunIISummer16MiniAODv2/WZToLNu2QorQQ2L_aTGC_13TeV-madgraph-pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/120000/24920A9C-47C8-E611-A8E5-A0000420FE80.root

@perrozzi

**Comment by perrozzi** [comment]
this particular sample is not needed (aTGC) but the problem indeed could should up for pythia only samples etc
is there a way to avoid the "Found zero products matching all criteria" error?
As far as I know, in the cfg one can add something like "don't exit' when you find an exception but I am not sure what to do at c++ code level. 
any example?

**Comment by perrozzi** [comment]
should be fixed in https://github.com/vhbb/cmssw/commit/7d62f3177a2c0d538a8d54f90712715aa9ab470a sorry I didn't realize I was pushing to vhbb directly...
