### ISSUE TITLE
pos/neg weight counter

### ISSUE THREAD

**Issue by jpata** [vhbb/cmssw#72]
for the aMC@NLO samples we have to keep track of the effective number of events

Neff = N(genWeight>0) - N(genWeight<0)

inclusively. Shall I make a PR for the Count histogram, adding 2 more bins with the pos/neg count?

@arizzi

**Comment by arizzi** [comment]
we usually had different histos for different counting
Il 17/giu/2015 16:30, "Joosep Pata" <notifications@github.com> ha scritto:

**Comment by jpata** [comment]
Added 2 additional separate histos with neg/pos weight count in PR #67, commit 42ceb7.

**Comment by jpata** [comment]
was closed by #67
