### ISSUE TITLE
True primary vertex information

### ISSUE THREAD

**Issue by silviodonato** [vhbb/cmssw#86]
At the moment in the ntuple we can't identify the events with the wrong reconstructed primary vertex.
This information it can be added with one of the following variables:
- z-coordinate of true PV and reco PV;
- delta z between true and reco PV;
- a flag that says if delta z between true and reco PV is below a threshold (eg. 1 mm).

**Comment by silviodonato** [comment]
(for V13 milestone)

**Comment by arizzi** [comment]
@silviodonato any chance to make a PR for this in the next 24h so that we have it in V12?

**Comment by silviodonato** [comment]
I don't think so...:(

**Comment by arizzi** [comment]
any chance for a PR in the next days?

**Comment by silviodonato** [comment]
I think so

**Comment by silviodonato** [comment]
Ready: https://github.com/vhbb/cmssw/pull/144.

Tested plotting:
tree->Draw("primaryVertices_z[0]-simPrimaryVertex_z","abs(primaryVertices_z[0]-simPrimaryVertex_z)<1")
It gives a peak in zero with a width below 20 um.
