### ISSUE TITLE
Duplicates in TTbar 'GenLep' collection

### ISSUE THREAD

**Issue by scooperstein** [vhbb/cmssw#94]
Hi,

I have been using the 'GenLep' collection in the V11 step2 ntuples. I notice that in the V11 sample 'TT_Tune4C_13TeV-pythia8-tauola', there is a problem with duplicated lepton entries. When there are two items in the collection for an event, i.e. 'nGenLep==2', the particle entries GenLep[0] and GenLep[1] are identical. When there are four items, the first and the third leptons, and the second and the fourth leptons, are identical. I took a quick look at some of the other V11 samples and I don't see this issue.

I would have expected that for ttbar the two 'GenLep' leptons would be the leptons from the decay of the two W's from the two tops, so they should be different particles. Am I misinterpreting the intention of this variable, or is this a bug?

Also, what does it mean when 'nGenLep==4'. Are there actually four real leptons from W's in the event? If so, how?

Cheers,
Stephane

**Comment by scooperstein** [comment]
I notice that there are almost no events with 'nGenLep==1' or 'nGenLep==3'. I wonder if in this sample, the cases where 'nGenLep==2' correspond to only one actual gen. lepton which has been duplicated? Similarly, 'nGenLep==4' events are probably events that actually have only two gen. leptons.

Stephane

**Comment by arizzi** [comment]
do they have the same status?

**Comment by capalmer85** [comment]
They do have the same status.  Below is a an example.  They are always
the same when there are two.


root [3]  tree->Scan("nGenLep:GenLep_pdgId:GenLep_pt:GenLep_status:GenLep_pt[0]==GenLep_pt[1]","nGenLep>1")
***********************************************************************************
*    Row   * Instance *   nGenLep * GenLep_pd * GenLep_pt * GenLep_st
* GenLep_pt *
***********************************************************************************
*        4 *        0 *         2 *       -13 * 60.986717 *        23
*         1 *
*        4 *        1 *         2 *       -13 * 60.986717 *        23
*         1 *
*        6 *        0 *         4 *       -13 * 16.211113 *        23
*         0 *
*        6 *        1 *         4 *        11 * 25.924377 *         1
*         0 *
*        6 *        2 *         4 *       -13 * 16.211113 *        23
*         0 *
*        6 *        3 *         4 *        11 * 25.924377 *         1
*         0 *
*        7 *        0 *         4 *       -13 * 64.292770 *        23
*         0 *
*        7 *        1 *         4 *        13 * 98.032707 *         1
*         0 *
*        7 *        2 *         4 *       -13 * 64.292770 *        23
*         0 *
*        7 *        3 *         4 *        13 * 98.032707 *         1
*         0 *
*       10 *        0 *         2 *        11 * 11.800931 *         1
*         1 *
*       10 *        1 *         2 *        11 * 11.800931 *         1
*         1 *
*       12 *        0 *         2 *       -11 * 24.556602 *        23
*         1 *
*       12 *        1 *         2 *       -11 * 24.556602 *        23
*         1 *
*       15 *        0 *         2 *       -13 * 197.39500 *         1
*         1 *
*       15 *        1 *         2 *       -13 * 197.39500 *         1
*         1 *
*       16 *        0 *         2 *        11 * 83.309135 *        23
*         1 *
*       16 *        1 *         2 *        11 * 83.309135 *        23
*         1 *
*       17 *        0 *         2 *        11 * 57.135505 *        23
*         1 *
*       17 *        1 *         2 *        11 * 57.135505 *        23
*         1 *

root [4] tree->GetEntries("nGenLep==2")
(Long64_t) 974198
root [5] tree->GetEntries("nGenLep==2 && GenLep_pt[0]==GenLep_pt[1]")
(Long64_t) 974198

**Comment by arizzi** [comment]
did you check on V12 (T12) testing samples?

**Comment by capalmer85** [comment]
No.  I will do that now.

**Comment by capalmer85** [comment]
In the files in

arizzi/VHBBHeppyT12/TT_TuneCUETP8M1_13TeV-powheg-scaledown-pythia8

I do NOT see this feature.  No duplicates.  Are these the files I should
check or a different set?

**Comment by arizzi** [comment]
those are ok, the new generator has no such feature
Il 17/lug/2015 18:17, "capalmer85" <notifications@github.com> ha scritto:
